// WC-EXT 5 helper: generate the const P-256 base table once.
// Run via:
//   cargo run -p rusty-web-crypto --release --example gen_p256_base_table > pilots/web-crypto/derived/src/p256_base_table.rs
// Then commit the resulting source file. Build-time const-evaluation
// realizes Doc 731 §XV.g Regime 1 (build-time bake).

use rusty_web_crypto::{curve_p256, p256_scalar_mul_base, BigUInt, P256Point};

fn main() {
    // Use the public p256_scalar_mul_base API to compute 2^i · G for
    // i in 0..256. It internally precomputes via the OnceLock table,
    // so the first call costs ~3s and populates everything we need.
    // We then re-extract each multiple by scalar-mul'ing G with 2^i.
    //
    // Simpler: replicate the internal logic directly.
    let c = curve_p256();
    let mut table: Vec<P256Point> = Vec::with_capacity(256);
    table.push(c.g.clone());
    // ec_double is private; use p256_scalar_mul_base with scalar 2 to
    // get 2·G, then 4·G, etc. Each call is O(table init) once, then
    // O(1) per add. Fine for a one-shot generator.
    let _ = p256_scalar_mul_base(&BigUInt::one()); // prime the OnceLock
    for i in 1..256 {
        // 2^i = 1 << i, encoded as BigUInt big-endian.
        let mut bytes = vec![0u8; 33];
        bytes[32 - i / 8] |= 1 << (i % 8);
        let scalar = BigUInt::from_be_bytes(&bytes);
        table.push(p256_scalar_mul_base(&scalar));
    }

    // Emit Rust source.
    println!("// AUTO-GENERATED by examples/gen_p256_base_table.rs.");
    println!("// WC-EXT 5 / Doc 731 §XV.g Regime 1 (build-time bake) for");
    println!("// the precomputed P-256 generator multiples table.");
    println!("// Do not edit by hand; re-generate via:");
    println!("//   cargo run -p rusty-web-crypto --release --example gen_p256_base_table");
    println!("//   > pilots/web-crypto/derived/src/p256_base_table.rs");
    println!();
    println!("use crate::{{P256Point, BigUInt}};");
    println!();
    println!("/// 256 affine multiples of the P-256 generator G:");
    println!("/// [G, 2·G, 4·G, ..., 2^255·G]. Used by p256_scalar_mul_base");
    println!("/// to eliminate runtime doublings on the u1·G half of ECDSA");
    println!("/// verify. Init cost: zero (const-evaluated at module init).");
    println!("pub fn p256_base_table_baked() -> Vec<P256Point> {{");
    println!("    let mut t = Vec::with_capacity(256);");
    for pt in &table {
        match pt {
            P256Point::Identity => println!("    t.push(P256Point::Identity);"),
            P256Point::Affine { x, y } => {
                let xh = hex_be(x);
                let yh = hex_be(y);
                println!("    t.push(P256Point::Affine {{");
                println!("        x: BigUInt::from_be_bytes(&hex_lit(\"{}\")),", xh);
                println!("        y: BigUInt::from_be_bytes(&hex_lit(\"{}\")),", yh);
                println!("    }});");
            }
        }
    }
    println!("    t");
    println!("}}");
    println!();
    println!("fn hex_lit(s: &str) -> Vec<u8> {{");
    println!("    (0..s.len()).step_by(2)");
    println!("        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())");
    println!("        .collect()");
    println!("}}");
}

fn hex_be(b: &BigUInt) -> String {
    let bytes = b.to_be_bytes(32);
    bytes.iter().map(|x| format!("{:02x}", x)).collect()
}
