//! Lower every translated spec section and emit a single generated.rs body
//! ready to be dropped into rusty-js-runtime/derived/src/generated.rs.
//!
//! Run with: `cargo run --example build_generated_rs -p rusty-js-ir > /tmp/generated.rs`

use rusty_js_ir::lower_to_rust;
use rusty_js_ir::sections::{
    array_prototype_find as find, array_prototype_index_search as index_search,
    array_prototype_iteration as iter, array_prototype_map,
    array_prototype_reduce as reduce, global_predicates, math_unary,
    number_static, object_integrity, object_proto_ops, object_static,
    promise_static, reflect_static,
};

fn main() {
    println!("//! Generated by rusty-js-ir lowering (resolver-instance #0c).");
    println!("//! Do not edit by hand; modify the IR in");
    println!("//! pilots/rusty-js-ir/derived/src/sections/.");
    println!();
    println!("use crate::interp::{{Runtime, RuntimeError}};");
    println!("use crate::value::Value;");
    println!();

    let sections = vec![
        array_prototype_map::build(),
        iter::build_for_each(),
        iter::build_filter(),
        iter::build_every(),
        iter::build_some(),
        find::build_find(),
        find::build_find_index(),
        find::build_find_last(),
        find::build_find_last_index(),
        index_search::build_index_of(),
        index_search::build_includes(),
        reduce::build_reduce(),
        object_static::build_keys(),
        object_static::build_values(),
        object_static::build_entries(),
        promise_static::build_resolve(),
        promise_static::build_reject(),
        object_proto_ops::build_get_prototype_of(),
        object_proto_ops::build_set_prototype_of(),
        object_proto_ops::build_is_extensible(),
        object_proto_ops::build_is_frozen(),
        object_proto_ops::build_is_sealed(),
        object_integrity::build_freeze(),
        object_integrity::build_seal(),
        object_integrity::build_prevent_extensions(),
        object_integrity::build_has_own(),
        object_integrity::build_is(),
        number_static::build_is_finite(),
        number_static::build_is_integer(),
        number_static::build_is_nan(),
        number_static::build_is_safe_integer(),
        global_predicates::build_is_nan(),
        global_predicates::build_is_finite(),
        math_unary::build_abs(),
        math_unary::build_floor(),
        math_unary::build_ceil(),
        math_unary::build_round(),
        math_unary::build_trunc(),
        math_unary::build_sqrt(),
        math_unary::build_cbrt(),
        math_unary::build_sign(),
        math_unary::build_exp(), math_unary::build_expm1(),
        math_unary::build_log(), math_unary::build_log1p(),
        math_unary::build_log2(), math_unary::build_log10(),
        math_unary::build_sin(), math_unary::build_cos(), math_unary::build_tan(),
        math_unary::build_asin(), math_unary::build_acos(), math_unary::build_atan(),
        math_unary::build_sinh(), math_unary::build_cosh(), math_unary::build_tanh(),
        math_unary::build_asinh(), math_unary::build_acosh(), math_unary::build_atanh(),
        reflect_static::build_has(),
        reflect_static::build_get(),
        reflect_static::build_set(),
        reflect_static::build_delete_property(),
        reflect_static::build_own_keys(),
    ];

    for f in &sections {
        println!("{}", lower_to_rust(f));
    }
}
