//! Lower every translated spec section and emit a single generated.rs body
//! ready to be dropped into rusty-js-runtime/derived/src/generated.rs.
//!
//! Run with: `cargo run --example build_generated_rs -p rusty-js-ir > /tmp/generated.rs`

use rusty_js_ir::lower_to_rust;
use rusty_js_ir::sections::{
    array_prototype_find as find, array_prototype_index_search as index_search,
    array_prototype_iteration as iter, array_prototype_map,
    array_prototype_reduce as reduce, object_proto_ops, object_static,
    promise_static,
};

fn main() {
    println!("//! Generated by rusty-js-ir lowering (resolver-instance #0c).");
    println!("//! Do not edit by hand; modify the IR in");
    println!("//! pilots/rusty-js-ir/derived/src/sections/.");
    println!();
    println!("use crate::interp::{{Runtime, RuntimeError}};");
    println!("use crate::value::Value;");
    println!();

    let sections = vec![
        array_prototype_map::build(),
        iter::build_for_each(),
        iter::build_filter(),
        iter::build_every(),
        iter::build_some(),
        find::build_find(),
        find::build_find_index(),
        find::build_find_last(),
        find::build_find_last_index(),
        index_search::build_index_of(),
        index_search::build_includes(),
        reduce::build_reduce(),
        object_static::build_keys(),
        object_static::build_values(),
        object_static::build_entries(),
        promise_static::build_resolve(),
        promise_static::build_reject(),
        object_proto_ops::build_get_prototype_of(),
        object_proto_ops::build_set_prototype_of(),
        object_proto_ops::build_is_extensible(),
        object_proto_ops::build_is_frozen(),
        object_proto_ops::build_is_sealed(),
    ];

    for f in &sections {
        println!("{}", lower_to_rust(f));
    }
}
