//! Lower every translated spec section and emit a single generated.rs body
//! ready to be dropped into rusty-js-runtime/derived/src/generated.rs.
//!
//! Run with: `cargo run --example build_generated_rs -p rusty-js-ir > /tmp/generated.rs`

use rusty_js_ir::lower_to_rust;
use rusty_js_ir::sections::{array_prototype_iteration as iter, array_prototype_map};

fn main() {
    println!("//! Generated by rusty-js-ir lowering (resolver-instance #0c).");
    println!("//! Do not edit by hand; modify the IR in");
    println!("//! pilots/rusty-js-ir/derived/src/sections/.");
    println!();
    println!("use crate::interp::{{Runtime, RuntimeError}};");
    println!("use crate::value::Value;");
    println!();

    let sections = vec![
        array_prototype_map::build(),
        iter::build_for_each(),
        iter::build_filter(),
        iter::build_every(),
        iter::build_some(),
    ];

    for f in &sections {
        println!("{}", lower_to_rust(f));
    }
}
