//! Run the spec-vs-IR linter against every translated section.
//!
//! Run with: `cargo run --example lint_all -p rusty-js-ir`

use rusty_js_ir::lint::lint;
use rusty_js_ir::sections::array_prototype_mutators as mutators;
use rusty_js_ir::sections::object_prototype as objproto;
use rusty_js_ir::sections::misc_static as misc;
use rusty_js_ir::sections::{
    array_prototype_find as find, array_prototype_index_search as index_search,
    array_prototype_iteration as iter, array_prototype_map,
    array_prototype_reduce as reduce, global_predicates, math_binary_variadic,
    math_unary, number_prototype, number_static, object_integrity,
    array_set_length, object_descriptors, object_proto_ops, object_static,
    promise_static, reflect_static, string_prototype,
};

fn main() {
    let sections = vec![
        ("Array.prototype.map", array_prototype_map::build(), array_prototype_map::spec_steps()),
        ("Array.prototype.forEach", iter::build_for_each(), iter::spec_steps_for_each()),
        ("Array.prototype.filter", iter::build_filter(), iter::spec_steps_filter()),
        ("Array.prototype.every", iter::build_every(), iter::spec_steps_every()),
        ("Array.prototype.some", iter::build_some(), iter::spec_steps_some()),
        ("Array.prototype.find", find::build_find(), find::spec_steps_find()),
        ("Array.prototype.findIndex", find::build_find_index(), find::spec_steps_find()),
        ("Array.prototype.findLast", find::build_find_last(), find::spec_steps_find_last()),
        ("Array.prototype.findLastIndex", find::build_find_last_index(), find::spec_steps_find_last_index()),
        ("Array.prototype.indexOf", index_search::build_index_of(), index_search::spec_steps_index_of()),
        ("Array.prototype.includes", index_search::build_includes(), index_search::spec_steps_includes()),
        ("Array.prototype.reduce", reduce::build_reduce(), reduce::spec_steps_reduce()),
        ("Array.prototype.push",    mutators::build_push(),    mutators::spec_steps_push()),
        ("Array.prototype.pop",     mutators::build_pop(),     mutators::spec_steps_pop()),
        ("Array.prototype.shift",   mutators::build_shift(),   mutators::spec_steps_shift()),
        ("Array.prototype.unshift", mutators::build_unshift(), mutators::spec_steps_unshift()),
        ("Array.prototype.reverse", mutators::build_reverse(), mutators::spec_steps_reverse()),
        ("Array.prototype.slice",         mutators::build_slice(),         mutators::spec_steps_slice()),
        ("Array.prototype.splice",        mutators::build_splice(),        mutators::spec_steps_splice()),
        ("Array.prototype.concat",        mutators::build_concat(),        mutators::spec_steps_concat()),
        ("Array.prototype.join",          mutators::build_join(),          mutators::spec_steps_join()),
        ("Array.prototype.at",            mutators::build_at(),            mutators::spec_steps_at()),
        ("Array.prototype.fill",          mutators::build_fill(),          mutators::spec_steps_fill()),
        ("Array.prototype.lastIndexOf",   mutators::build_last_index_of(), mutators::spec_steps_last_index_of()),
        ("Array.prototype.reduceRight",   mutators::build_reduce_right(),  mutators::spec_steps_reduce_right()),
        ("Array.prototype.copyWithin",    mutators::build_copy_within(),   mutators::spec_steps_copy_within()),
        ("Array.prototype.flat",          mutators::build_flat(),          mutators::spec_steps_flat()),
        ("Array.prototype.flatMap",       mutators::build_flat_map(),      mutators::spec_steps_flat_map()),
        ("Array.prototype.toReversed",     mutators::build_to_reversed(),      mutators::spec_steps_to_reversed()),
        ("Array.prototype.toSorted",       mutators::build_to_sorted(),        mutators::spec_steps_to_sorted()),
        ("Array.prototype.toSpliced",      mutators::build_to_spliced(),       mutators::spec_steps_to_spliced()),
        ("Array.prototype.with",           mutators::build_with(),             mutators::spec_steps_with()),
        ("Array.prototype.toLocaleString", mutators::build_to_locale_string(), mutators::spec_steps_to_locale_string()),
        ("Array.prototype.toString",       mutators::build_to_string(),        mutators::spec_steps_to_string()),
        ("Array.prototype.sort",           mutators::build_sort(),             mutators::spec_steps_sort()),
        ("Array.prototype.entries",        mutators::build_entries(),          mutators::spec_steps_entries()),
        ("Array.prototype.keys",           mutators::build_keys(),             mutators::spec_steps_keys()),
        ("Array.prototype.values",         mutators::build_values(),           mutators::spec_steps_values()),
        ("Object.prototype.toString",              objproto::build_to_string(),              objproto::spec_steps_to_string()),
        ("Object.prototype.hasOwnProperty",        objproto::build_has_own_property(),       objproto::spec_steps_has_own_property()),
        ("Object.prototype.valueOf",               objproto::build_value_of(),               objproto::spec_steps_value_of()),
        ("Object.prototype.propertyIsEnumerable",  objproto::build_property_is_enumerable(), objproto::spec_steps_property_is_enumerable()),
        ("Object.prototype.isPrototypeOf",         objproto::build_is_prototype_of(),        objproto::spec_steps_is_prototype_of()),
        ("Object.prototype.toLocaleString",        objproto::build_to_locale_string(),       objproto::spec_steps_to_locale_string()),
        ("Math.imul",     misc::build_math_imul(),   misc::spec_steps_math_imul()),
        ("Math.fround",   misc::build_math_fround(), misc::spec_steps_math_fround()),
        ("Math.clz32",    misc::build_math_clz32(),  misc::spec_steps_math_clz32()),
        ("Array.isArray", misc::build_is_array(),    misc::spec_steps_is_array()),
        ("Array.of",      misc::build_array_of(),    misc::spec_steps_array_of()),
        ("Number.prototype.toString",        misc::build_number_proto_to_string(),        misc::spec_steps_number_proto_to_string()),
        ("Number.prototype.toLocaleString",  misc::build_number_proto_to_locale_string(), misc::spec_steps_number_proto_to_locale_string()),
        ("String.fromCharCode",              misc::build_string_from_char_code(),         misc::spec_steps_string_from_char_code()),
        ("String.fromCodePoint",             misc::build_string_from_code_point(),        misc::spec_steps_string_from_code_point()),
        ("Error.prototype.toString",         misc::build_error_proto_to_string(),         misc::spec_steps_error_proto_to_string()),
        ("Symbol.prototype.toString",        misc::build_symbol_proto_to_string(),        misc::spec_steps_symbol_proto_to_string()),
        ("BigInt.prototype.toString",        misc::build_bigint_proto_to_string(),        misc::spec_steps_bigint_proto_to_string()),
        ("Function.prototype.toString",      misc::build_function_proto_to_string(),      misc::spec_steps_function_proto_to_string()),
        ("Date.prototype.getTime",            misc::build_date_get_time(),       misc::spec_steps_date_get_time()),
        ("Date.prototype.valueOf",            misc::build_date_value_of(),       misc::spec_steps_date_value_of()),
        ("Date.prototype.toISOString",        misc::build_date_to_iso_string(),  misc::spec_steps_date_to_iso_string()),
        ("Date.prototype.toDateString",       misc::build_date_to_date_string(), misc::spec_steps_date_to_date_string()),
        ("Date.prototype.toTimeString",       misc::build_date_to_time_string(), misc::spec_steps_date_to_time_string()),
        ("Date.prototype.toUTCString",        misc::build_date_to_utc_string(),  misc::spec_steps_date_to_utc_string()),
        ("Date.prototype.toString",           misc::build_date_to_string(),        misc::spec_steps_date_to_string()),
        ("Date.prototype.toJSON",             misc::build_date_to_json(),          misc::spec_steps_date_to_json()),
        ("Date.prototype.getFullYear",        misc::build_date_get_full_year(),    misc::spec_steps_date_get_full_year()),
        ("Date.prototype.getMonth",           misc::build_date_get_month(),        misc::spec_steps_date_get_month()),
        ("Date.prototype.getDate",            misc::build_date_get_date(),         misc::spec_steps_date_get_date()),
        ("Date.prototype.getDay",             misc::build_date_get_day(),          misc::spec_steps_date_get_day()),
        ("Date.prototype.getHours",           misc::build_date_get_hours(),        misc::spec_steps_date_get_hours()),
        ("Date.prototype.getMinutes",         misc::build_date_get_minutes(),      misc::spec_steps_date_get_minutes()),
        ("Date.prototype.getSeconds",         misc::build_date_get_seconds(),      misc::spec_steps_date_get_seconds()),
        ("Date.prototype.getMilliseconds",    misc::build_date_get_milliseconds(), misc::spec_steps_date_get_milliseconds()),
        ("Date.prototype.setTime",            misc::build_date_set_time(),         misc::spec_steps_date_set_time()),
        ("Date.prototype.setHours",           misc::build_date_set_hours(),        misc::spec_steps_date_set_hours()),
        ("Date.prototype.setMinutes",         misc::build_date_set_minutes(),      misc::spec_steps_date_set_minutes()),
        ("Date.prototype.setSeconds",         misc::build_date_set_seconds(),      misc::spec_steps_date_set_seconds()),
        ("Date.prototype.setMilliseconds",    misc::build_date_set_milliseconds(), misc::spec_steps_date_set_milliseconds()),
        ("Date.prototype.setDate",            misc::build_date_set_date(),         misc::spec_steps_date_set_date()),
        ("Date.prototype.setMonth",           misc::build_date_set_month(),        misc::spec_steps_date_set_month()),
        ("Date.prototype.setFullYear",        misc::build_date_set_full_year(),    misc::spec_steps_date_set_full_year()),
        ("String.raw",  misc::build_string_raw(),  misc::spec_steps_string_raw()),
        ("Array.from",  misc::build_array_from(),  misc::spec_steps_array_from()),
        ("Date.now",    misc::build_date_now(),    misc::spec_steps_date_now()),
        ("Date.parse",  misc::build_date_parse(),  misc::spec_steps_date_parse()),
        ("Date.UTC",    misc::build_date_utc(),    misc::spec_steps_date_utc()),
        ("Math.random",                       misc::build_math_random(),              misc::spec_steps_math_random()),
        ("Date.prototype.getTimezoneOffset",  misc::build_date_get_timezone_offset(), misc::spec_steps_date_get_timezone_offset()),
        ("parseInt",   misc::build_parse_int(),   misc::spec_steps_parse_int()),
        ("parseFloat", misc::build_parse_float(), misc::spec_steps_parse_float()),
        ("JSON.stringify",            misc::build_json_stringify(), misc::spec_steps_json_stringify()),
        ("JSON.parse",                misc::build_json_parse(),     misc::spec_steps_json_parse()),
        ("Symbol.for",                misc::build_symbol_for(),     misc::spec_steps_symbol_for()),
        ("Symbol.keyFor",             misc::build_symbol_key_for(), misc::spec_steps_symbol_key_for()),
        ("Date.prototype.getYear",    misc::build_date_get_year(),  misc::spec_steps_date_get_year()),
        ("Date.prototype.setYear",    misc::build_date_set_year(),  misc::spec_steps_date_set_year()),
        ("Object.groupBy",            misc::build_object_group_by(), misc::spec_steps_object_group_by()),
        ("Map.prototype.get",     misc::build_map_get(),      misc::spec_steps_map_get()),
        ("Map.prototype.set",     misc::build_map_set(),      misc::spec_steps_map_set()),
        ("Map.prototype.has",     misc::build_map_has(),      misc::spec_steps_map_has()),
        ("Map.prototype.delete",  misc::build_map_delete(),   misc::spec_steps_map_delete()),
        ("Map.prototype.clear",   misc::build_map_clear(),    misc::spec_steps_map_clear()),
        ("Map.prototype.forEach", misc::build_map_for_each(), misc::spec_steps_map_for_each()),
        ("Map.prototype.values",  misc::build_map_values(),   misc::spec_steps_map_values()),
        ("Map.prototype.keys",    misc::build_map_keys(),     misc::spec_steps_map_keys()),
        ("Map.prototype.entries", misc::build_map_entries(),  misc::spec_steps_map_entries()),
        ("Set.prototype.add",     misc::build_set_add(),      misc::spec_steps_set_add()),
        ("Set.prototype.has",     misc::build_set_has(),      misc::spec_steps_set_has()),
        ("Set.prototype.delete",  misc::build_set_delete(),   misc::spec_steps_set_delete()),
        ("Set.prototype.clear",   misc::build_set_clear(),    misc::spec_steps_set_clear()),
        ("Set.prototype.forEach", misc::build_set_for_each(), misc::spec_steps_set_for_each()),
        ("Set.prototype.union",               misc::build_set_union(),                misc::spec_steps_set_union()),
        ("Set.prototype.intersection",        misc::build_set_intersection(),         misc::spec_steps_set_intersection()),
        ("Set.prototype.difference",          misc::build_set_difference(),           misc::spec_steps_set_difference()),
        ("Set.prototype.symmetricDifference", misc::build_set_symmetric_difference(), misc::spec_steps_set_symmetric_difference()),
        ("Set.prototype.isSubsetOf",          misc::build_set_is_subset_of(),         misc::spec_steps_set_is_subset_of()),
        ("Set.prototype.isSupersetOf",        misc::build_set_is_superset_of(),       misc::spec_steps_set_is_superset_of()),
        ("Set.prototype.isDisjointFrom",      misc::build_set_is_disjoint_from(),     misc::spec_steps_set_is_disjoint_from()),
        ("Object.keys", object_static::build_keys(), object_static::spec_steps_keys()),
        ("Object.values", object_static::build_values(), object_static::spec_steps_values()),
        ("Object.entries", object_static::build_entries(), object_static::spec_steps_entries()),
        ("Promise.resolve", promise_static::build_resolve(), promise_static::spec_steps_resolve()),
        ("Promise.reject", promise_static::build_reject(), promise_static::spec_steps_reject()),
        ("Promise.prototype.then",    promise_static::build_then(),         promise_static::spec_steps_then()),
        ("Promise.prototype.catch",   promise_static::build_catch(),        promise_static::spec_steps_catch()),
        ("Promise.prototype.finally", promise_static::build_finally(),      promise_static::spec_steps_finally()),
        ("Promise.all",               promise_static::build_all(),          promise_static::spec_steps_all()),
        ("Promise.allSettled",        promise_static::build_all_settled(),  promise_static::spec_steps_all_settled()),
        ("Promise.any",               promise_static::build_any(),          promise_static::spec_steps_any()),
        ("Promise.race",              promise_static::build_race(),         promise_static::spec_steps_race()),
        ("Promise.withResolvers",     promise_static::build_with_resolvers(), promise_static::spec_steps_with_resolvers()),
        ("Promise.all Resolve Element Factory", promise_static::build_all_resolve_element_factory(), promise_static::spec_steps_all_resolve_element_factory()),
        ("Promise.allSettled Resolve Element Factory", promise_static::build_all_settled_resolve_element_factory(), promise_static::spec_steps_all_settled_resolve_element_factory()),
        ("Promise.allSettled Reject Element Factory", promise_static::build_all_settled_reject_element_factory(), promise_static::spec_steps_all_settled_reject_element_factory()),
        ("Promise.any Reject Element Factory", promise_static::build_any_reject_element_factory(), promise_static::spec_steps_any_reject_element_factory()),
        ("Object.defineProperty",            object_descriptors::build_define_property(), object_descriptors::spec_steps_define_property()),
        ("Object.defineProperties",          object_descriptors::build_define_properties(), object_descriptors::spec_steps_define_properties()),
        ("Object.getOwnPropertyDescriptor",  object_descriptors::build_get_own_property_descriptor(), object_descriptors::spec_steps_get_own_property_descriptor()),
        ("Object.getOwnPropertyDescriptors", object_descriptors::build_get_own_property_descriptors(), object_descriptors::spec_steps_get_own_property_descriptors()),
        ("Object.create",                    object_descriptors::build_create(), object_descriptors::spec_steps_create()),
        ("Object.prototype.__defineGetter__", object_descriptors::build_proto_define_getter(), object_descriptors::spec_steps_proto_define_getter()),
        ("Object.prototype.__defineSetter__", object_descriptors::build_proto_define_setter(), object_descriptors::spec_steps_proto_define_setter()),
        ("Object.prototype.__lookupGetter__", object_descriptors::build_proto_lookup_getter(), object_descriptors::spec_steps_proto_lookup_getter()),
        ("Object.prototype.__lookupSetter__", object_descriptors::build_proto_lookup_setter(), object_descriptors::spec_steps_proto_lookup_setter()),
        ("ArraySetLength (§10.4.2.1)", array_set_length::build_array_set_length(), array_set_length::spec_steps_array_set_length()),
        ("Object.getPrototypeOf", object_proto_ops::build_get_prototype_of(), object_proto_ops::spec_steps_get_prototype_of()),
        ("Object.setPrototypeOf", object_proto_ops::build_set_prototype_of(), object_proto_ops::spec_steps_set_prototype_of()),
        ("Object.isExtensible", object_proto_ops::build_is_extensible(), object_proto_ops::spec_steps_is_extensible()),
        ("Object.isFrozen", object_proto_ops::build_is_frozen(), object_proto_ops::spec_steps_is_frozen()),
        ("Object.isSealed", object_proto_ops::build_is_sealed(), object_proto_ops::spec_steps_is_sealed()),
        ("Object.freeze", object_integrity::build_freeze(), object_integrity::spec_steps_freeze()),
        ("Object.seal", object_integrity::build_seal(), object_integrity::spec_steps_seal()),
        ("Object.preventExtensions", object_integrity::build_prevent_extensions(), object_integrity::spec_steps_prevent_extensions()),
        ("Object.hasOwn", object_integrity::build_has_own(), object_integrity::spec_steps_has_own()),
        ("Object.is", object_integrity::build_is(), object_integrity::spec_steps_is()),
        ("Number.isFinite", number_static::build_is_finite(), number_static::spec_steps_is_finite()),
        ("Number.isInteger", number_static::build_is_integer(), number_static::spec_steps_is_integer()),
        ("Number.isNaN", number_static::build_is_nan(), number_static::spec_steps_is_nan()),
        ("Number.isSafeInteger", number_static::build_is_safe_integer(), number_static::spec_steps_is_safe_integer()),
        ("isNaN", global_predicates::build_is_nan(), global_predicates::spec_steps_is_nan()),
        ("isFinite", global_predicates::build_is_finite(), global_predicates::spec_steps_is_finite()),
        ("Math.abs",   math_unary::build_abs(),   math_unary::spec_steps_abs()),
        ("Math.floor", math_unary::build_floor(), math_unary::spec_steps_floor()),
        ("Math.ceil",  math_unary::build_ceil(),  math_unary::spec_steps_ceil()),
        ("Math.round", math_unary::build_round(), math_unary::spec_steps_round()),
        ("Math.trunc", math_unary::build_trunc(), math_unary::spec_steps_trunc()),
        ("Math.sqrt",  math_unary::build_sqrt(),  math_unary::spec_steps_sqrt()),
        ("Math.cbrt",  math_unary::build_cbrt(),  math_unary::spec_steps_cbrt()),
        ("Math.sign",  math_unary::build_sign(),  math_unary::spec_steps_sign()),
        ("Math.exp",   math_unary::build_exp(),   math_unary::spec_steps_exp()),
        ("Math.expm1", math_unary::build_expm1(), math_unary::spec_steps_expm1()),
        ("Math.log",   math_unary::build_log(),   math_unary::spec_steps_log()),
        ("Math.log1p", math_unary::build_log1p(), math_unary::spec_steps_log1p()),
        ("Math.log2",  math_unary::build_log2(),  math_unary::spec_steps_log2()),
        ("Math.log10", math_unary::build_log10(), math_unary::spec_steps_log10()),
        ("Math.sin",   math_unary::build_sin(),   math_unary::spec_steps_sin()),
        ("Math.cos",   math_unary::build_cos(),   math_unary::spec_steps_cos()),
        ("Math.tan",   math_unary::build_tan(),   math_unary::spec_steps_tan()),
        ("Math.asin",  math_unary::build_asin(),  math_unary::spec_steps_asin()),
        ("Math.acos",  math_unary::build_acos(),  math_unary::spec_steps_acos()),
        ("Math.atan",  math_unary::build_atan(),  math_unary::spec_steps_atan()),
        ("Math.sinh",  math_unary::build_sinh(),  math_unary::spec_steps_sinh()),
        ("Math.cosh",  math_unary::build_cosh(),  math_unary::spec_steps_cosh()),
        ("Math.tanh",  math_unary::build_tanh(),  math_unary::spec_steps_tanh()),
        ("Math.asinh", math_unary::build_asinh(), math_unary::spec_steps_asinh()),
        ("Math.acosh", math_unary::build_acosh(), math_unary::spec_steps_acosh()),
        ("Math.atanh", math_unary::build_atanh(), math_unary::spec_steps_atanh()),
        ("Reflect.has",            reflect_static::build_has(),             reflect_static::spec_steps_has()),
        ("Reflect.get",            reflect_static::build_get(),             reflect_static::spec_steps_get()),
        ("Reflect.set",            reflect_static::build_set(),             reflect_static::spec_steps_set()),
        ("Reflect.deleteProperty", reflect_static::build_delete_property(), reflect_static::spec_steps_delete_property()),
        ("Reflect.ownKeys",        reflect_static::build_own_keys(),        reflect_static::spec_steps_own_keys()),
        ("Reflect.getPrototypeOf", reflect_static::build_get_prototype_of(), reflect_static::spec_steps_get_prototype_of()),
        ("Reflect.setPrototypeOf", reflect_static::build_set_prototype_of(), reflect_static::spec_steps_set_prototype_of()),
        ("Reflect.isExtensible",   reflect_static::build_is_extensible(),   reflect_static::spec_steps_is_extensible()),
        ("Reflect.preventExtensions", reflect_static::build_prevent_extensions(), reflect_static::spec_steps_prevent_extensions()),
        ("Math.pow",   math_binary_variadic::build_pow(),   math_binary_variadic::spec_steps_pow()),
        ("Math.atan2", math_binary_variadic::build_atan2(), math_binary_variadic::spec_steps_atan2()),
        ("Math.max",   math_binary_variadic::build_max(),   math_binary_variadic::spec_steps_max()),
        ("Math.min",   math_binary_variadic::build_min(),   math_binary_variadic::spec_steps_min()),
        ("Math.hypot", math_binary_variadic::build_hypot(), math_binary_variadic::spec_steps_hypot()),
        ("Object.getOwnPropertyNames", object_static::build_get_own_property_names(), object_static::spec_steps_get_own_property_names()),
        ("Object.getOwnPropertySymbols", object_static::build_get_own_property_symbols(), object_static::spec_steps_get_own_property_symbols()),
        ("Object.assign", object_static::build_assign(), object_static::spec_steps_assign()),
        ("Object.fromEntries", object_static::build_from_entries(), object_static::spec_steps_from_entries()),
        ("Number.prototype.toFixed", number_prototype::build_to_fixed(), number_prototype::spec_steps_to_fixed()),
        ("Number.prototype.valueOf", number_prototype::build_value_of(), number_prototype::spec_steps_value_of()),
        ("Number.prototype.toExponential", number_prototype::build_to_exponential(), number_prototype::spec_steps_to_exponential()),
        ("Number.prototype.toPrecision", number_prototype::build_to_precision(), number_prototype::spec_steps_to_precision()),
        ("Boolean.prototype.valueOf", number_prototype::build_boolean_value_of(), number_prototype::spec_steps_boolean_value_of()),
        ("Boolean.prototype.toString", number_prototype::build_boolean_to_string(), number_prototype::spec_steps_boolean_to_string()),
        ("String.prototype.charAt",     string_prototype::build_char_at(),      string_prototype::spec_steps_char_at()),
        ("String.prototype.charCodeAt", string_prototype::build_char_code_at(), string_prototype::spec_steps_char_code_at()),
        ("String.prototype.concat",     string_prototype::build_concat(),       string_prototype::spec_steps_concat()),
        ("String.prototype.toLowerCase", string_prototype::build_to_lower_case(), string_prototype::spec_steps_to_lower_case()),
        ("String.prototype.toUpperCase", string_prototype::build_to_upper_case(), string_prototype::spec_steps_to_upper_case()),
        ("String.prototype.toLocaleLowerCase", string_prototype::build_to_locale_lower_case(), string_prototype::spec_steps_to_locale_lower_case()),
        ("String.prototype.toLocaleUpperCase", string_prototype::build_to_locale_upper_case(), string_prototype::spec_steps_to_locale_upper_case()),
        ("String.prototype.trim",       string_prototype::build_trim(),       string_prototype::spec_steps_trim()),
        ("String.prototype.trimStart",  string_prototype::build_trim_start(), string_prototype::spec_steps_trim_start()),
        ("String.prototype.trimEnd",    string_prototype::build_trim_end(),   string_prototype::spec_steps_trim_end()),
        ("String.prototype.trimLeft",   string_prototype::build_trim_left(),  string_prototype::spec_steps_trim_left()),
        ("String.prototype.trimRight",  string_prototype::build_trim_right(), string_prototype::spec_steps_trim_right()),
        ("String.prototype.repeat",     string_prototype::build_repeat(),     string_prototype::spec_steps_repeat()),
        ("String.prototype.padStart",   string_prototype::build_pad_start(),  string_prototype::spec_steps_pad_start()),
        ("String.prototype.padEnd",     string_prototype::build_pad_end(),    string_prototype::spec_steps_pad_end()),
        ("String.prototype.slice",         string_prototype::build_slice(),         string_prototype::spec_steps_slice()),
        ("String.prototype.substring",     string_prototype::build_substring(),     string_prototype::spec_steps_substring()),
        ("String.prototype.substr",        string_prototype::build_substr(),        string_prototype::spec_steps_substr()),
        ("String.prototype.indexOf",       string_prototype::build_index_of(),      string_prototype::spec_steps_index_of()),
        ("String.prototype.lastIndexOf",   string_prototype::build_last_index_of(), string_prototype::spec_steps_last_index_of()),
        ("String.prototype.includes",      string_prototype::build_includes(),      string_prototype::spec_steps_includes()),
        ("String.prototype.startsWith",    string_prototype::build_starts_with(),   string_prototype::spec_steps_starts_with()),
        ("String.prototype.endsWith",      string_prototype::build_ends_with(),     string_prototype::spec_steps_ends_with()),
        ("String.prototype.codePointAt",   string_prototype::build_code_point_at(),  string_prototype::spec_steps_code_point_at()),
        ("String.prototype.at",            string_prototype::build_at(),             string_prototype::spec_steps_at()),
        ("String.prototype.normalize",     string_prototype::build_normalize(),      string_prototype::spec_steps_normalize()),
        ("String.prototype.localeCompare", string_prototype::build_locale_compare(), string_prototype::spec_steps_locale_compare()),
        ("String.prototype.split",         string_prototype::build_split(),         string_prototype::spec_steps_split()),
        ("String.prototype.replace",       string_prototype::build_replace(),       string_prototype::spec_steps_replace()),
        ("String.prototype.replaceAll",    string_prototype::build_replace_all(),   string_prototype::spec_steps_replace_all()),
    ];

    let mut total_unexpected = 0;
    for (name, f, spec) in &sections {
        // Filter the spec_steps list to drop synthetic-inline records
        // (matching the linter's collect_steps convention from
        // lint.rs). The hand-authored records still carry these for
        // documentation; the diff doesn't track them.
        let filtered_spec: Vec<_> = spec.iter()
            .filter(|r| !r.step_id.ends_with(".throw")
                && !r.step_id.ends_with(".guard")
                && !r.step_id.ends_with(".return")
                && !r.step_id.ends_with(".adj")
                && !r.step_id.ends_with(".seed"))
            .cloned()
            .collect();
        let report = lint(f, &filtered_spec);
        // Filter out known param.* binding-convention findings — those
        // are not in any spec section's algorithm step list.
        let unexpected: Vec<_> = report.findings.iter()
            .filter(|f| !f.spec_step.starts_with("param."))
            .collect();
        if unexpected.is_empty() {
            println!("✓ {} — OK", name);
        } else {
            println!("✗ {} — {} unexpected findings:", name, unexpected.len());
            for f in &unexpected {
                println!("    step {}: {}", f.spec_step, f.message);
            }
            total_unexpected += unexpected.len();
        }
    }

    println!();
    if total_unexpected == 0 {
        println!("All {} translated sections lint clean.", sections.len());
    } else {
        println!("{} total unexpected findings across {} sections.", total_unexpected, sections.len());
        std::process::exit(1);
    }
}
