//! Lowering: IR → Rust source per IR-DESIGN.md §3 + §5.
//!
//! Resolver-instance #0c per IR-DESIGN.md §0. Stage-deterministic: the same
//! IRFunction always produces the same Rust source. No optimization passes
//! in Tier 1; the lowering is purely mechanical.

use crate::ir::{Expr, IRFunction, IRNode, Slot, Step};

/// Lower an IRFunction to Rust source. The output is a `pub fn` with the
/// canonical Runtime/Value/RuntimeError signature, ready to be included
/// into rusty-js-runtime/derived/src/generated.rs.
pub fn lower_to_rust(f: &IRFunction) -> String {
    let mut out = String::new();
    // Preamble — spec-traceability comment + signature.
    out.push_str(&format!(
        "/// ECMA-262 §{} — {}\n",
        f.spec_section, f.title
    ));
    out.push_str(
        "///\n/// Generated by rusty-js-ir lowering (resolver-instance #0c).\n",
    );
    out.push_str(
        "/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.\n",
    );
    out.push_str(&format!(
        "pub fn {}(rt: &mut Runtime, this: Value, args: &[Value])\n    -> Result<Value, RuntimeError>\n{{\n",
        f.rust_name
    ));
    for step in &f.body {
        emit_step(&mut out, step, 1);
    }
    out.push_str("}\n");
    out
}

fn indent(out: &mut String, depth: usize) {
    for _ in 0..depth {
        out.push_str("    ");
    }
}

fn emit_step(out: &mut String, step: &Step, depth: usize) {
    indent(out, depth);
    out.push_str(&format!("// step {} (§{} step {})\n", step.spec_step, step.spec_step, step.spec_step.replace('.', ".")));
    emit_node(out, &step.node, depth);
}

fn emit_node(out: &mut String, node: &IRNode, depth: usize) {
    match node {
        IRNode::Let { name, value } => {
            indent(out, depth);
            // Use `let mut` so subsequent Assign nodes targeting this name
            // typecheck. Rust's unused_mut lint will fire for never-reassigned
            // Lets, which is acceptable in IR-generated code where the lint
            // is broadly suppressed.
            out.push_str(&format!("let mut {} = {};\n", name, emit_expr(value)));
        }
        IRNode::LetIndex { name, value } => {
            indent(out, depth);
            out.push_str(&format!("let mut {}: usize = {};\n", name, emit_expr(value)));
        }
        IRNode::AssignIndex { name, value } => {
            indent(out, depth);
            out.push_str(&format!("{} = {};\n", name, emit_expr(value)));
        }
        IRNode::Assign { name, value } => {
            indent(out, depth);
            out.push_str(&format!("{} = {};\n", name, emit_expr(value)));
        }
        IRNode::Throw { class, message } => {
            indent(out, depth);
            out.push_str(&format!(
                "return Err(RuntimeError::{}({:?}.into()));\n",
                class.rust_variant(),
                message
            ));
        }
        IRNode::Return(e) => {
            indent(out, depth);
            out.push_str(&format!("return Ok({});\n", emit_expr(e)));
        }
        IRNode::If {
            cond,
            then_body,
            else_body,
        } => {
            indent(out, depth);
            out.push_str(&format!("if {} {{\n", emit_expr(cond)));
            for s in then_body {
                emit_step(out, s, depth + 1);
            }
            indent(out, depth);
            if !else_body.is_empty() {
                out.push_str("} else {\n");
                for s in else_body {
                    emit_step(out, s, depth + 1);
                }
                indent(out, depth);
            }
            out.push_str("}\n");
        }
        IRNode::While { cond, body } => {
            indent(out, depth);
            out.push_str(&format!("while {} {{\n", emit_expr(cond)));
            for s in body {
                emit_step(out, s, depth + 1);
            }
            indent(out, depth);
            out.push_str("}\n");
        }
        IRNode::Expr(e) => {
            indent(out, depth);
            out.push_str(&format!("{};\n", emit_expr(e)));
        }
        IRNode::CellSet { cell, value } => {
            indent(out, depth);
            out.push_str(&format!("*{}.borrow_mut() = {};\n", emit_expr(cell), emit_expr(value)));
        }
    }
}

/// Emit a property-key access as a borrowed string slice. Literal
/// Expr::Str values lower to `"literal"`; dynamic keys lower through
/// `&abstract_ops::to_string(&<value>).as_str().to_string()`.
fn emit_property_key(e: &Expr) -> String {
    match e {
        Expr::Str(s) => format!("{:?}", s),
        // For Var bindings already typed as &str (e.g. IndexAsKey), the
        // caller passes the &str directly. Fall back to to_string coerce.
        Expr::Var(_) | Expr::IndexAsKey(_) => format!("&{}", emit_expr(e)),
        // Dynamic Value-typed expressions: coerce to String, then borrow.
        _ => format!(
            "&crate::abstract_ops::to_string(&{}).as_str().to_string()",
            emit_expr(e)),
    }
}

fn emit_expr(e: &Expr) -> String {
    match e {
        // ── Constants / refs ──
        // Vars are cloned on read; for usize-typed locals (LoopIndex)
        // .clone() is a Copy-no-op, and for Value locals it produces
        // the per-use clone the surrounding callsite needs.
        Expr::Var(name) => format!("{}.clone()", name),
        Expr::Undefined => "Value::Undefined".into(),
        Expr::Null => "Value::Null".into(),
        Expr::Bool(b) => format!("Value::Boolean({})", b),
        Expr::Number(n) => format!("Value::Number({}_f64)", n),
        Expr::Str(s) => format!("Value::String(std::rc::Rc::new({:?}.to_string()))", s),
        Expr::Arg(i) => format!(
            "args.get({}).cloned().unwrap_or(Value::Undefined)",
            i
        ),
        Expr::This => "this.clone()".into(),
        Expr::HasArg(i) => format!("(args.len() > {})", i),
        Expr::AllArgs => "args_slice_for_builtin".into(),
        Expr::ArgsRest(start) => format!("if args.len() > {} {{ &args[{}..] }} else {{ &[] }}", start, start),
        Expr::CallBuiltin { name, args } => {
            // CallBuiltin args are passed by reference (matches the
            // convention of the existing IR-target helpers
            // rt.to_object / rt.coerce_to_string / etc.). The `.clone()`
            // expansion of Var produces a temporary that the `&` borrows.
            // Special case: Expr::AllArgs lowers to the raw `args` slice
            // without a `&` prefix (the helper takes `&[Value]` directly).
            let args_str = args.iter()
                .map(|a| match a {
                    Expr::AllArgs => "args".into(),
                    // ArgsRest already emits `&args[start..]`; don't double-prefix.
                    Expr::ArgsRest(start) => format!(
                        "if args.len() > {} {{ &args[{}..] }} else {{ &[] }}",
                        start, start),
                    _ => format!("&{}", emit_expr(a)),
                })
                .collect::<Vec<_>>().join(", ");
            format!("rt.{}({})?", name, args_str)
        }
        Expr::IntConst(n) => format!("{}_usize", n),
        Expr::AsIndex(v) => format!("rt.value_to_index(&{})?", emit_expr(v)),
        Expr::IndexAsValue(v) => format!("Value::Number({} as f64)", emit_expr(v)),
        Expr::IndexAsKey(v) => format!("{}.to_string()", emit_expr(v)),
        Expr::IndexAdd(l, r) => format!("({} + {})", emit_expr(l), emit_expr(r)),

        // ── Ω.5.P63.E55 Alphabet closures ──
        Expr::CellNew(init) => format!(
            "std::rc::Rc::new(std::cell::RefCell::new({}))", emit_expr(init)),
        Expr::CellGet(cell) => format!("(*{}.borrow()).clone()", emit_expr(cell)),
        Expr::Closure { label, params, captures, body } => {
            let mut s = String::from("{\n");
            // Clone each captured local so the move-closure owns its copy.
            for c in captures {
                s.push_str(&format!("            let {} = {}.clone();\n", c, c));
            }
            // §10.2.10 — function .length matches the declared parameter
            // count. Use make_native_with_length so the IR-derived closure
            // exposes the correct .length to test262 probes.
            s.push_str(&format!(
                "            let __native = crate::intrinsics::make_native_with_length(\"{}\", {},\n",
                label, params.len()));
            s.push_str("                move |rt, args| {\n");
            // Param bindings — each closure param reads from args[i].
            for (i, p) in params.iter().enumerate() {
                s.push_str(&format!(
                    "                    let {} = args.get({}).cloned().unwrap_or(Value::Undefined);\n",
                    p, i));
            }
            // Suppress unused-variable lint when a closure body doesn't
            // touch every captured / every param.
            for c in captures { s.push_str(&format!("                    let _ = &{};\n", c)); }
            for p in params { s.push_str(&format!("                    let _ = &{};\n", p)); }
            // Body.
            for step in body { emit_step(&mut s, step, 5); }
            // Default return.
            s.push_str("                    Ok(Value::Undefined)\n");
            s.push_str("                });\n");
            s.push_str("            Value::Object(rt.alloc_object(__native))\n");
            s.push_str("        }");
            s
        }

        // ── Coercion / type-check (§A8.29) ──
        Expr::RequireObjectCoercible(v) => {
            // Side-effecting check — returns Value::Undefined as a no-op
            // expression-result; the lowering uses it in an Expr-step so
            // the error propagates via `?`.
            format!("{{ rt.require_object_coercible(&{})?; {} }}", emit_expr(v), emit_expr(v))
        }
        Expr::ToObject(v) => format!("rt.to_object(&{})?", emit_expr(v)),
        Expr::ToPrimitive(v, hint) => {
            format!("rt.to_primitive(&{}, {:?})?", emit_expr(v), hint)
        }
        Expr::ToString(v) => format!("rt.to_string_strict(&{})?", emit_expr(v)),
        Expr::ToNumber(v) => format!("rt.coerce_to_number(&{})?", emit_expr(v)),
        Expr::ToInteger(v) => format!("rt.to_integer(&{})?", emit_expr(v)),
        Expr::ToLength(v) => format!("rt.to_length(&{})?", emit_expr(v)),
        Expr::ToUint32(v) => format!("rt.to_uint32(&{})?", emit_expr(v)),
        Expr::ToBoolean(v) => {
            // Returns Rust `bool` (not Value::Boolean) — matches ECMA spec
            // abstract-op return type. The IR should not wrap an already-
            // bool expression in another ToBoolean; lowering would produce
            // bool-of-bool which is invalid in Rust.
            format!("crate::abstract_ops::to_boolean(&{})", emit_expr(v))
        }
        Expr::ToPropertyKey(v) => format!("rt.to_property_key(&{})?", emit_expr(v)),
        Expr::IsCallable(v) => format!("rt.is_callable(&{})", emit_expr(v)),
        Expr::IsConstructor(v) => format!("rt.is_constructor(&{})", emit_expr(v)),
        Expr::IsArray(v) => format!("rt.is_array(&{})", emit_expr(v)),
        Expr::IsRegExp(v) => format!("rt.is_regexp_strict(&{})?", emit_expr(v)),
        Expr::SameValue(a, b) => {
            format!("crate::abstract_ops::same_value(&{}, &{})", emit_expr(a), emit_expr(b))
        }
        Expr::SameValueZero(a, b) => {
            format!("crate::abstract_ops::same_value_zero(&{}, &{})", emit_expr(a), emit_expr(b))
        }

        // ── Slot / property (§A8.28 + §A8.30) ──
        Expr::HasSlot(o, slot) => match slot {
            Slot::Named(name) => format!("rt.has_named_slot(&{}, {:?})", emit_expr(o), name),
            Slot::Sentinel(s) => format!("rt.has_sentinel(&{}, {:?})", emit_expr(o), s),
        },
        Expr::GetSlot(o, slot) => match slot {
            Slot::Named(name) => format!("rt.get_named_slot(&{}, {:?})?", emit_expr(o), name),
            Slot::Sentinel(s) => format!("rt.get_sentinel(&{}, {:?})?", emit_expr(o), s),
        },
        // Property-access helpers take a &str key. When the IR key is a
        // literal Expr::Str, emit the borrowed string slice directly; for
        // dynamic keys we route through abstract_ops::to_string at call
        // site.
        Expr::Get(o, p) => {
            let key = emit_property_key(p);
            format!("rt.read_property_via(&{}, {})?", emit_expr(o), key)
        }
        Expr::SpecGet(o, p) => {
            let key = emit_property_key(p);
            format!("rt.spec_get(&{}, {})?", emit_expr(o), key)
        }
        Expr::HasProperty(o, p) => {
            let key = emit_property_key(p);
            format!("rt.has_property_via(&{}, {})", emit_expr(o), key)
        }
        Expr::HasOwnProperty(o, p) => {
            let key = emit_property_key(p);
            format!("rt.has_own_property_via(&{}, {})", emit_expr(o), key)
        }
        Expr::OrdinaryObjectCreate { proto, slots } => {
            let slot_inits: Vec<String> = slots
                .iter()
                .map(|(s, v)| match s {
                    Slot::Named(n) => format!("({:?}.to_string(), {})", n, emit_expr(v)),
                    Slot::Sentinel(n) => format!("({:?}.to_string(), {})", n, emit_expr(v)),
                })
                .collect();
            format!(
                "rt.ordinary_object_create(&{}, vec![{}])",
                emit_expr(proto),
                slot_inits.join(", ")
            )
        }
        Expr::ArraySpeciesCreate { o, length } => format!(
            "rt.array_species_create(&{}, {})?",
            emit_expr(o),
            emit_expr(length)
        ),

        // ── Calls (§A8.32 extended) ──
        Expr::Call {
            function,
            this,
            args,
        } => {
            let args_vec = format!("vec![{}]",
                args.iter().map(emit_expr).collect::<Vec<_>>().join(", "));
            format!(
                "rt.call_function({}.clone(), {}.clone(), {})?",
                emit_expr(function),
                emit_expr(this),
                args_vec
            )
        }
        Expr::Construct { ctor, args } => {
            let args_vec = format!("vec![{}]",
                args.iter().map(emit_expr).collect::<Vec<_>>().join(", "));
            format!("rt.construct_function({}.clone(), {})?", emit_expr(ctor), args_vec)
        }
        Expr::Invoke {
            object,
            method,
            args,
        } => {
            let args_vec = format!("vec![{}]",
                args.iter().map(emit_expr).collect::<Vec<_>>().join(", "));
            format!(
                "rt.invoke_method(&{}, &{}, {})?",
                emit_expr(object),
                emit_expr(method),
                args_vec
            )
        }

        // ── Operators (§A8.32) ──
        Expr::OpAdd(l, r) => format!("rt.op_add_rt(&{}, &{})?", emit_expr(l), emit_expr(r)),
        Expr::OpSub(l, r) => format!("rt.op_sub_rt(&{}, &{})?", emit_expr(l), emit_expr(r)),
        Expr::OpMul(l, r) => format!("rt.op_mul_rt(&{}, &{})?", emit_expr(l), emit_expr(r)),
        Expr::LooseEq(a, b) => {
            format!("Value::Boolean(rt.is_loosely_equal_rt(&{}, &{})?)", emit_expr(a), emit_expr(b))
        }
        Expr::StrictEq(a, b) => {
            // Returns Rust `bool` (matches §7.2.15 return type). Wrap with
            // Value::Boolean(...) at the IR level when a Value is needed.
            format!(
                "crate::abstract_ops::is_strictly_equal(&{}, &{})",
                emit_expr(a),
                emit_expr(b)
            )
        }
        Expr::Lt(a, b) => format!("({} < {})", emit_expr(a), emit_expr(b)),
        Expr::Le(a, b) => format!("({} <= {})", emit_expr(a), emit_expr(b)),
        Expr::Not(v) => format!("!{}", emit_expr(v)),

        // IR-EXT 67 Number-typed arithmetic — dispatches through
        // coerce_to_number at the runtime boundary and returns Value-typed
        // results. The bool-returning variants (NumberLt/Ge) wrap in
        // Value::Boolean per IR convention.
        Expr::NumberAdd(a, b) => format!(
            "Value::Number(rt.coerce_to_number(&{})? + rt.coerce_to_number(&{})?)",
            emit_expr(a), emit_expr(b)),
        Expr::NumberSub(a, b) => format!(
            "Value::Number(rt.coerce_to_number(&{})? - rt.coerce_to_number(&{})?)",
            emit_expr(a), emit_expr(b)),
        // NumberLt/NumberGe return raw bool (matching Expr::Lt convention)
        // so they slot directly into IR If/While conditions without an
        // extra ToBoolean wrapping. Use Expr::ToBoolean explicitly to lift
        // into a Value::Boolean for value contexts.
        Expr::NumberLt(a, b) => format!(
            "(rt.coerce_to_number(&{})? < rt.coerce_to_number(&{})?)",
            emit_expr(a), emit_expr(b)),
        Expr::NumberGe(a, b) => format!(
            "(rt.coerce_to_number(&{})? >= rt.coerce_to_number(&{})?)",
            emit_expr(a), emit_expr(b)),

        // IR-EXT 68 alphabet promotion: §13.5.3 typeof. Returns
        // Value::String. Routes through Runtime::type_of_value.
        Expr::TypeOf(e) => format!(
            "Value::String(std::rc::Rc::new(rt.type_of_value(&{}).to_string()))",
            emit_expr(e)),
        Expr::LengthOfArrayLike(o) => format!("rt.length_of_array_like(&{})?", emit_expr(o)),
        Expr::CreateDataPropertyOrThrow(o, p, v) => format!(
            "{{ rt.create_data_property_or_throw(&{}, &{}, {})?; Value::Undefined }}",
            emit_expr(o),
            emit_expr(p),
            emit_expr(v)
        ),
    }
}

/// Free-form constructor for `Var` expressions — saves typing.
pub fn var(name: &str) -> Expr {
    Expr::Var(name.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{ErrorClass, Expr, IRFunction, IRNode, Step};

    #[test]
    fn lower_minimal_throw() {
        let f = IRFunction {
            spec_section: "X.Y.Z".into(),
            rust_name: "demo".into(),
            title: "demo()".into(),
            body: vec![Step {
                spec_step: "1".into(),
                node: IRNode::Throw {
                    class: ErrorClass::TypeError,
                    message: "demo".into(),
                },
            }],
        };
        let rust = lower_to_rust(&f);
        assert!(rust.contains("RuntimeError::TypeError"));
        assert!(rust.contains("§X.Y.Z"));
    }
}
