//! Generated by rusty-js-ir lowering (resolver-instance #0c).
//! Do not edit by hand; modify the IR in
//! pilots/rusty-js-ir/derived/src/sections/.

use crate::interp::{Runtime, RuntimeError};
use crate::value::Value;

/// ECMA-262 §23.1.3.20 — Array.prototype.map ( callbackfn [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_map(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.callbackfn (§param.callbackfn step param.callbackfn)
    let callbackfn = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&callbackfn.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.map: callback is not callable".into()));
    }
    // step 4 (§4 step 4)
    let a = rt.array_species_create(&o.clone(), len.clone())?;
    // step 5 (§5 step 5)
    let mut k: usize = 0_usize;
    // step 6 (§6 step 6)
    while (k.clone() < len.clone()) {
        // step 6.a (§6.a step 6.a)
        let pk = k.clone().to_string();
        // step 6.b (§6.b step 6.b)
        let k_present = rt.has_property_via(&o.clone(), &pk.clone());
        // step 6.c (§6.c step 6.c)
        if k_present.clone() {
            // step 6.c.i (§6.c.i step 6.c.i)
            let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
            // step 6.c.ii (§6.c.ii step 6.c.ii)
            let mapped = rt.call_function(callbackfn.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?;
            // step 6.c.iii (§6.c.iii step 6.c.iii)
            { rt.create_data_property_or_throw(&a.clone(), &pk.clone(), mapped.clone())?; Value::Undefined };
        }
        // step 6.d (§6.d step 6.d)
        k = (k.clone() + 1_usize);
    }
    // step 7 (§7 step 7)
    return Ok(a.clone());
}

/// ECMA-262 §23.1.3.15 — Array.prototype.forEach ( callbackfn [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_for_each(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.callbackfn (§param.callbackfn step param.callbackfn)
    let callbackfn = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&callbackfn.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.forEach: callback is not callable".into()));
    }
    // step 4 (§4 step 4)
    let mut k: usize = 0_usize;
    // step 5 (§5 step 5)
    while (k.clone() < len.clone()) {
        // step 5.a (§5.a step 5.a)
        let pk = k.clone().to_string();
        // step 5.b (§5.b step 5.b)
        if rt.has_property_via(&o.clone(), &pk.clone()) {
            // step 5.c.i (§5.c.i step 5.c.i)
            let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
            // step 5.c.ii (§5.c.ii step 5.c.ii)
            rt.call_function(callbackfn.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?;
        }
        // step 5.d (§5.d step 5.d)
        k = (k.clone() + 1_usize);
    }
    // step 6 (§6 step 6)
    return Ok(Value::Undefined);
}

/// ECMA-262 §23.1.3.7 — Array.prototype.filter ( callbackfn [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_filter(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.callbackfn (§param.callbackfn step param.callbackfn)
    let callbackfn = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&callbackfn.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.filter: callback is not callable".into()));
    }
    // step 4 (§4 step 4)
    let a = rt.array_species_create(&o.clone(), 0_usize)?;
    // step 5 (§5 step 5)
    let mut k: usize = 0_usize;
    // step 6 (§6 step 6)
    let mut to: usize = 0_usize;
    // step 7 (§7 step 7)
    while (k.clone() < len.clone()) {
        // step 7.a (§7.a step 7.a)
        let pk = k.clone().to_string();
        // step 7.b (§7.b step 7.b)
        if rt.has_property_via(&o.clone(), &pk.clone()) {
            // step 7.c.i (§7.c.i step 7.c.i)
            let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
            // step 7.c.ii (§7.c.ii step 7.c.ii)
            let selected = crate::abstract_ops::to_boolean(&rt.call_function(callbackfn.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?);
            // step 7.c.iii (§7.c.iii step 7.c.iii)
            if selected.clone() {
                // step 7.c.iii.1 (§7.c.iii.1 step 7.c.iii.1)
                { rt.create_data_property_or_throw(&a.clone(), &to.clone().to_string(), k_value.clone())?; Value::Undefined };
                // step 7.c.iii.2 (§7.c.iii.2 step 7.c.iii.2)
                to = (to.clone() + 1_usize);
            }
        }
        // step 7.d (§7.d step 7.d)
        k = (k.clone() + 1_usize);
    }
    // step 8 (§8 step 8)
    return Ok(a.clone());
}

/// ECMA-262 §23.1.3.6 — Array.prototype.every ( callbackfn [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_every(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.callbackfn (§param.callbackfn step param.callbackfn)
    let callbackfn = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&callbackfn.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.every: callback is not callable".into()));
    }
    // step 4 (§4 step 4)
    let mut k: usize = 0_usize;
    // step 5 (§5 step 5)
    while (k.clone() < len.clone()) {
        // step 5.a (§5.a step 5.a)
        let pk = k.clone().to_string();
        // step 5.b (§5.b step 5.b)
        if rt.has_property_via(&o.clone(), &pk.clone()) {
            // step 5.c.i (§5.c.i step 5.c.i)
            let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
            // step 5.c.ii (§5.c.ii step 5.c.ii)
            let test_result = crate::abstract_ops::to_boolean(&rt.call_function(callbackfn.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?);
            // step 5.c.iii (§5.c.iii step 5.c.iii)
            if !test_result.clone() {
                // step 5.c.iii.1 (§5.c.iii.1 step 5.c.iii.1)
                return Ok(Value::Boolean(false));
            }
        }
        // step 5.d (§5.d step 5.d)
        k = (k.clone() + 1_usize);
    }
    // step 6 (§6 step 6)
    return Ok(Value::Boolean(true));
}

/// ECMA-262 §23.1.3.29 — Array.prototype.some ( callbackfn [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_some(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.callbackfn (§param.callbackfn step param.callbackfn)
    let callbackfn = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&callbackfn.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.some: callback is not callable".into()));
    }
    // step 4 (§4 step 4)
    let mut k: usize = 0_usize;
    // step 5 (§5 step 5)
    while (k.clone() < len.clone()) {
        // step 5.a (§5.a step 5.a)
        let pk = k.clone().to_string();
        // step 5.b (§5.b step 5.b)
        if rt.has_property_via(&o.clone(), &pk.clone()) {
            // step 5.c.i (§5.c.i step 5.c.i)
            let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
            // step 5.c.ii (§5.c.ii step 5.c.ii)
            let test_result = crate::abstract_ops::to_boolean(&rt.call_function(callbackfn.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?);
            // step 5.c.iii (§5.c.iii step 5.c.iii)
            if test_result.clone() {
                // step 5.c.iii.1 (§5.c.iii.1 step 5.c.iii.1)
                return Ok(Value::Boolean(true));
            }
        }
        // step 5.d (§5.d step 5.d)
        k = (k.clone() + 1_usize);
    }
    // step 6 (§6 step 6)
    return Ok(Value::Boolean(false));
}

/// ECMA-262 §23.1.3.8 — Array.prototype.find ( predicate [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_find(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.predicate (§param.predicate step param.predicate)
    let predicate = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&predicate.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.find: predicate is not callable".into()));
    }
    // step 4 (§4 step 4)
    let mut k: usize = 0_usize;
    // step 5 (§5 step 5)
    while (k.clone() < len.clone()) {
        // step 5.a (§5.a step 5.a)
        let pk = k.clone().to_string();
        // step 5.b (§5.b step 5.b)
        let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
        // step 5.c (§5.c step 5.c)
        let test_result = crate::abstract_ops::to_boolean(&rt.call_function(predicate.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?);
        // step 5.d (§5.d step 5.d)
        if test_result.clone() {
            // step 5.d.i (§5.d.i step 5.d.i)
            return Ok(k_value.clone());
        }
        // step 5.e (§5.e step 5.e)
        k = (k.clone() + 1_usize);
    }
    // step 6 (§6 step 6)
    return Ok(Value::Undefined);
}

/// ECMA-262 §23.1.3.9 — Array.prototype.findIndex ( predicate [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_find_index(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.predicate (§param.predicate step param.predicate)
    let predicate = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&predicate.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.findIndex: predicate is not callable".into()));
    }
    // step 4 (§4 step 4)
    let mut k: usize = 0_usize;
    // step 5 (§5 step 5)
    while (k.clone() < len.clone()) {
        // step 5.a (§5.a step 5.a)
        let pk = k.clone().to_string();
        // step 5.b (§5.b step 5.b)
        let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
        // step 5.c (§5.c step 5.c)
        let test_result = crate::abstract_ops::to_boolean(&rt.call_function(predicate.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?);
        // step 5.d (§5.d step 5.d)
        if test_result.clone() {
            // step 5.d.i (§5.d.i step 5.d.i)
            return Ok(Value::Number(k.clone() as f64));
        }
        // step 5.e (§5.e step 5.e)
        k = (k.clone() + 1_usize);
    }
    // step 6 (§6 step 6)
    return Ok(Value::Number(-1_f64));
}

/// ECMA-262 §23.1.3.10 — Array.prototype.findLast ( predicate [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_find_last(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.predicate (§param.predicate step param.predicate)
    let predicate = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&predicate.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.findLast: predicate is not callable".into()));
    }
    // step 4 (§4 step 4)
    let mut k: usize = 0_usize;
    // step param.last (§param.last step param.last)
    let mut last = Value::Undefined;
    // step 5 (§5 step 5)
    while (k.clone() < len.clone()) {
        // step 5.a (§5.a step 5.a)
        let pk = k.clone().to_string();
        // step 5.b (§5.b step 5.b)
        let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
        // step 5.c (§5.c step 5.c)
        let test_result = crate::abstract_ops::to_boolean(&rt.call_function(predicate.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?);
        // step 5.d (§5.d step 5.d)
        if test_result.clone() {
            // step 5.d.i (§5.d.i step 5.d.i)
            last = k_value.clone();
        }
        // step 5.e (§5.e step 5.e)
        k = (k.clone() + 1_usize);
    }
    // step 6 (§6 step 6)
    return Ok(last.clone());
}

/// ECMA-262 §23.1.3.11 — Array.prototype.findLastIndex ( predicate [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_find_last_index(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.predicate (§param.predicate step param.predicate)
    let predicate = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&predicate.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.findLastIndex: predicate is not callable".into()));
    }
    // step 4 (§4 step 4)
    let mut k: usize = 0_usize;
    // step param.last (§param.last step param.last)
    let mut last = Value::Number(-1_f64);
    // step 5 (§5 step 5)
    while (k.clone() < len.clone()) {
        // step 5.a (§5.a step 5.a)
        let pk = k.clone().to_string();
        // step 5.b (§5.b step 5.b)
        let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
        // step 5.c (§5.c step 5.c)
        let test_result = crate::abstract_ops::to_boolean(&rt.call_function(predicate.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?);
        // step 5.d (§5.d step 5.d)
        if test_result.clone() {
            // step 5.d.i (§5.d.i step 5.d.i)
            last = Value::Number(k.clone() as f64);
        }
        // step 5.e (§5.e step 5.e)
        k = (k.clone() + 1_usize);
    }
    // step 6 (§6 step 6)
    return Ok(last.clone());
}

/// ECMA-262 §23.1.3.16 — Array.prototype.indexOf ( searchElement [ , fromIndex ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_index_of(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.searchElement (§param.searchElement step param.searchElement)
    let search_element = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !(0_usize < len.clone()) {
        // step 3.return (§3.return step 3.return)
        return Ok(Value::Number(-1_f64));
    }
    // step 8 (§8 step 8)
    let mut k: usize = 0_usize;
    // step 9 (§9 step 9)
    while (k.clone() < len.clone()) {
        // step 9.a (§9.a step 9.a)
        let pk = k.clone().to_string();
        // step 9.b (§9.b step 9.b)
        let k_present = rt.has_property_via(&o.clone(), &pk.clone());
        // step 9.c (§9.c step 9.c)
        if k_present.clone() {
            // step 9.c.i (§9.c.i step 9.c.i)
            let elem = rt.read_property_via(&o.clone(), &pk.clone())?;
            // step 9.c.ii (§9.c.ii step 9.c.ii)
            if crate::abstract_ops::is_strictly_equal(&search_element.clone(), &elem.clone()) {
                // step 9.c.ii.1 (§9.c.ii.1 step 9.c.ii.1)
                return Ok(Value::Number(k.clone() as f64));
            }
        }
        // step 9.d (§9.d step 9.d)
        k = (k.clone() + 1_usize);
    }
    // step 10 (§10 step 10)
    return Ok(Value::Number(-1_f64));
}

/// ECMA-262 §23.1.3.13 — Array.prototype.includes ( searchElement [ , fromIndex ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_includes(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.searchElement (§param.searchElement step param.searchElement)
    let search_element = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !(0_usize < len.clone()) {
        // step 3.return (§3.return step 3.return)
        return Ok(Value::Boolean(false));
    }
    // step 8 (§8 step 8)
    let mut k: usize = 0_usize;
    // step 9 (§9 step 9)
    while (k.clone() < len.clone()) {
        // step 9.a (§9.a step 9.a)
        let pk = k.clone().to_string();
        // step 9.b (§9.b step 9.b)
        let elem = rt.read_property_via(&o.clone(), &pk.clone())?;
        // step 9.c (§9.c step 9.c)
        if crate::abstract_ops::same_value_zero(&search_element.clone(), &elem.clone()) {
            // step 9.c.i (§9.c.i step 9.c.i)
            return Ok(Value::Boolean(true));
        }
        // step 9.d (§9.d step 9.d)
        k = (k.clone() + 1_usize);
    }
    // step 10 (§10 step 10)
    return Ok(Value::Boolean(false));
}

/// ECMA-262 §23.1.3.24 — Array.prototype.reduce ( callbackfn [ , initialValue ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_reduce(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.callbackfn (§param.callbackfn step param.callbackfn)
    let callbackfn = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&callbackfn.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.reduce: callback is not callable".into()));
    }
    // step 4 (§4 step 4)
    if !(0_usize < len.clone()) {
        // step 4.guard (§4.guard step 4.guard)
        if !(args.len() > 1) {
            // step 4.throw (§4.throw step 4.throw)
            return Err(RuntimeError::TypeError("Reduce of empty array with no initial value".into()));
        }
    }
    // step 5 (§5 step 5)
    let mut k: usize = 0_usize;
    // step 6 (§6 step 6)
    let mut accumulator = Value::Undefined;
    // step 7 (§7 step 7)
    if (args.len() > 1) {
        // step 7.a (§7.a step 7.a)
        accumulator = args.get(1).cloned().unwrap_or(Value::Undefined);
    } else {
        // step 7.b (§7.b step 7.b)
        if (k.clone() < len.clone()) {
            // step 7.b.iv (§7.b.iv step 7.b.iv)
            accumulator = rt.read_property_via(&o.clone(), &k.clone().to_string())?;
            // step 7.b.v (§7.b.v step 7.b.v)
            k = (k.clone() + 1_usize);
        }
    }
    // step 8 (§8 step 8)
    while (k.clone() < len.clone()) {
        // step 8.a (§8.a step 8.a)
        let pk = k.clone().to_string();
        // step 8.b (§8.b step 8.b)
        if rt.has_property_via(&o.clone(), &pk.clone()) {
            // step 8.c.i (§8.c.i step 8.c.i)
            let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
            // step 8.c.ii (§8.c.ii step 8.c.ii)
            accumulator = rt.call_function(callbackfn.clone().clone(), Value::Undefined.clone(), vec![accumulator.clone(), k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?;
        }
        // step 8.d (§8.d step 8.d)
        k = (k.clone() + 1_usize);
    }
    // step 9 (§9 step 9)
    return Ok(accumulator.clone());
}

/// ECMA-262 §20.1.2.18 — Object.keys ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_keys(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let obj = rt.to_object(&target.clone())?;
    // step 2 (§2 step 2)
    return Ok(rt.enumerable_own_keys(&obj.clone())?);
}

/// ECMA-262 §20.1.2.23 — Object.values ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_values(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let obj = rt.to_object(&target.clone())?;
    // step 2 (§2 step 2)
    return Ok(rt.enumerable_own_values(&obj.clone())?);
}

/// ECMA-262 §20.1.2.5 — Object.entries ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_entries(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let obj = rt.to_object(&target.clone())?;
    // step 2 (§2 step 2)
    return Ok(rt.enumerable_own_entries(&obj.clone())?);
}

/// ECMA-262 §27.2.4.7 — Promise.resolve ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn promise_resolve(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.promise_resolve_via(&x.clone())?);
}

/// ECMA-262 §27.2.4.5 — Promise.reject ( r )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn promise_reject(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.r (§param.r step param.r)
    let reason = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.promise_reject_via(&reason.clone())?);
}

/// ECMA-262 §20.1.2.12 — Object.getPrototypeOf ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_get_prototype_of(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let obj = rt.to_object(&target.clone())?;
    // step 2 (§2 step 2)
    return Ok(rt.get_prototype_of_via(&obj.clone())?);
}

/// ECMA-262 §20.1.2.21 — Object.setPrototypeOf ( O, proto )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_set_prototype_of(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.proto (§param.proto step param.proto)
    let proto = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&target.clone())?;
    // step 2 (§2 step 2)
    return Ok(rt.set_prototype_of_via(&o.clone(), &proto.clone())?);
}

/// ECMA-262 §20.1.2.14 — Object.isExtensible ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_is_extensible(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.is_extensible_via(&target.clone())?);
}

/// ECMA-262 §20.1.2.16 — Object.isFrozen ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_is_frozen(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.is_frozen_via(&target.clone())?);
}

/// ECMA-262 §20.1.2.17 — Object.isSealed ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_is_sealed(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.is_sealed_via(&target.clone())?);
}

