//! Generated by rusty-js-ir lowering (resolver-instance #0c).
//! Do not edit by hand; modify the IR in
//! pilots/rusty-js-ir/derived/src/sections/.

use crate::interp::{Runtime, RuntimeError};
use crate::value::Value;

/// ECMA-262 §23.1.3.20 — Array.prototype.map ( callbackfn [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_map(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.callbackfn (§param.callbackfn step param.callbackfn)
    let callbackfn = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&callbackfn.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.map: callback is not callable".into()));
    }
    // step 4 (§4 step 4)
    let a = rt.array_species_create(&o.clone(), len.clone())?;
    // step 5 (§5 step 5)
    let mut k: usize = 0_usize;
    // step 6 (§6 step 6)
    while (k.clone() < len.clone()) {
        // step 6.a (§6.a step 6.a)
        let pk = k.clone().to_string();
        // step 6.b (§6.b step 6.b)
        let k_present = rt.has_property_via(&o.clone(), &pk.clone());
        // step 6.c (§6.c step 6.c)
        if k_present.clone() {
            // step 6.c.i (§6.c.i step 6.c.i)
            let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
            // step 6.c.ii (§6.c.ii step 6.c.ii)
            let mapped = rt.call_function(callbackfn.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?;
            // step 6.c.iii (§6.c.iii step 6.c.iii)
            { rt.create_data_property_or_throw(&a.clone(), &pk.clone(), mapped.clone())?; Value::Undefined };
        }
        // step 6.d (§6.d step 6.d)
        k = (k.clone() + 1_usize);
    }
    // step 7 (§7 step 7)
    return Ok(a.clone());
}

/// ECMA-262 §23.1.3.15 — Array.prototype.forEach ( callbackfn [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_for_each(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.callbackfn (§param.callbackfn step param.callbackfn)
    let callbackfn = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&callbackfn.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.forEach: callback is not callable".into()));
    }
    // step 4 (§4 step 4)
    let mut k: usize = 0_usize;
    // step 5 (§5 step 5)
    while (k.clone() < len.clone()) {
        // step 5.a (§5.a step 5.a)
        let pk = k.clone().to_string();
        // step 5.b (§5.b step 5.b)
        if rt.has_property_via(&o.clone(), &pk.clone()) {
            // step 5.c.i (§5.c.i step 5.c.i)
            let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
            // step 5.c.ii (§5.c.ii step 5.c.ii)
            rt.call_function(callbackfn.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?;
        }
        // step 5.d (§5.d step 5.d)
        k = (k.clone() + 1_usize);
    }
    // step 6 (§6 step 6)
    return Ok(Value::Undefined);
}

/// ECMA-262 §23.1.3.7 — Array.prototype.filter ( callbackfn [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_filter(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.callbackfn (§param.callbackfn step param.callbackfn)
    let callbackfn = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&callbackfn.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.filter: callback is not callable".into()));
    }
    // step 4 (§4 step 4)
    let a = rt.array_species_create(&o.clone(), 0_usize)?;
    // step 5 (§5 step 5)
    let mut k: usize = 0_usize;
    // step 6 (§6 step 6)
    let mut to: usize = 0_usize;
    // step 7 (§7 step 7)
    while (k.clone() < len.clone()) {
        // step 7.a (§7.a step 7.a)
        let pk = k.clone().to_string();
        // step 7.b (§7.b step 7.b)
        if rt.has_property_via(&o.clone(), &pk.clone()) {
            // step 7.c.i (§7.c.i step 7.c.i)
            let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
            // step 7.c.ii (§7.c.ii step 7.c.ii)
            let selected = crate::abstract_ops::to_boolean(&rt.call_function(callbackfn.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?);
            // step 7.c.iii (§7.c.iii step 7.c.iii)
            if selected.clone() {
                // step 7.c.iii.1 (§7.c.iii.1 step 7.c.iii.1)
                { rt.create_data_property_or_throw(&a.clone(), &to.clone().to_string(), k_value.clone())?; Value::Undefined };
                // step 7.c.iii.2 (§7.c.iii.2 step 7.c.iii.2)
                to = (to.clone() + 1_usize);
            }
        }
        // step 7.d (§7.d step 7.d)
        k = (k.clone() + 1_usize);
    }
    // step 8 (§8 step 8)
    return Ok(a.clone());
}

/// ECMA-262 §23.1.3.6 — Array.prototype.every ( callbackfn [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_every(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.callbackfn (§param.callbackfn step param.callbackfn)
    let callbackfn = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&callbackfn.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.every: callback is not callable".into()));
    }
    // step 4 (§4 step 4)
    let mut k: usize = 0_usize;
    // step 5 (§5 step 5)
    while (k.clone() < len.clone()) {
        // step 5.a (§5.a step 5.a)
        let pk = k.clone().to_string();
        // step 5.b (§5.b step 5.b)
        if rt.has_property_via(&o.clone(), &pk.clone()) {
            // step 5.c.i (§5.c.i step 5.c.i)
            let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
            // step 5.c.ii (§5.c.ii step 5.c.ii)
            let test_result = crate::abstract_ops::to_boolean(&rt.call_function(callbackfn.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?);
            // step 5.c.iii (§5.c.iii step 5.c.iii)
            if !test_result.clone() {
                // step 5.c.iii.1 (§5.c.iii.1 step 5.c.iii.1)
                return Ok(Value::Boolean(false));
            }
        }
        // step 5.d (§5.d step 5.d)
        k = (k.clone() + 1_usize);
    }
    // step 6 (§6 step 6)
    return Ok(Value::Boolean(true));
}

/// ECMA-262 §23.1.3.29 — Array.prototype.some ( callbackfn [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_some(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.callbackfn (§param.callbackfn step param.callbackfn)
    let callbackfn = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&callbackfn.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.some: callback is not callable".into()));
    }
    // step 4 (§4 step 4)
    let mut k: usize = 0_usize;
    // step 5 (§5 step 5)
    while (k.clone() < len.clone()) {
        // step 5.a (§5.a step 5.a)
        let pk = k.clone().to_string();
        // step 5.b (§5.b step 5.b)
        if rt.has_property_via(&o.clone(), &pk.clone()) {
            // step 5.c.i (§5.c.i step 5.c.i)
            let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
            // step 5.c.ii (§5.c.ii step 5.c.ii)
            let test_result = crate::abstract_ops::to_boolean(&rt.call_function(callbackfn.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?);
            // step 5.c.iii (§5.c.iii step 5.c.iii)
            if test_result.clone() {
                // step 5.c.iii.1 (§5.c.iii.1 step 5.c.iii.1)
                return Ok(Value::Boolean(true));
            }
        }
        // step 5.d (§5.d step 5.d)
        k = (k.clone() + 1_usize);
    }
    // step 6 (§6 step 6)
    return Ok(Value::Boolean(false));
}

/// ECMA-262 §23.1.3.8 — Array.prototype.find ( predicate [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_find(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.predicate (§param.predicate step param.predicate)
    let predicate = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&predicate.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.find: predicate is not callable".into()));
    }
    // step 4 (§4 step 4)
    let mut k: usize = 0_usize;
    // step 5 (§5 step 5)
    while (k.clone() < len.clone()) {
        // step 5.a (§5.a step 5.a)
        let pk = k.clone().to_string();
        // step 5.b (§5.b step 5.b)
        let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
        // step 5.c (§5.c step 5.c)
        let test_result = crate::abstract_ops::to_boolean(&rt.call_function(predicate.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?);
        // step 5.d (§5.d step 5.d)
        if test_result.clone() {
            // step 5.d.i (§5.d.i step 5.d.i)
            return Ok(k_value.clone());
        }
        // step 5.e (§5.e step 5.e)
        k = (k.clone() + 1_usize);
    }
    // step 6 (§6 step 6)
    return Ok(Value::Undefined);
}

/// ECMA-262 §23.1.3.9 — Array.prototype.findIndex ( predicate [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_find_index(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.predicate (§param.predicate step param.predicate)
    let predicate = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&predicate.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.findIndex: predicate is not callable".into()));
    }
    // step 4 (§4 step 4)
    let mut k: usize = 0_usize;
    // step 5 (§5 step 5)
    while (k.clone() < len.clone()) {
        // step 5.a (§5.a step 5.a)
        let pk = k.clone().to_string();
        // step 5.b (§5.b step 5.b)
        let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
        // step 5.c (§5.c step 5.c)
        let test_result = crate::abstract_ops::to_boolean(&rt.call_function(predicate.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?);
        // step 5.d (§5.d step 5.d)
        if test_result.clone() {
            // step 5.d.i (§5.d.i step 5.d.i)
            return Ok(Value::Number(k.clone() as f64));
        }
        // step 5.e (§5.e step 5.e)
        k = (k.clone() + 1_usize);
    }
    // step 6 (§6 step 6)
    return Ok(Value::Number(-1_f64));
}

/// ECMA-262 §23.1.3.10 — Array.prototype.findLast ( predicate [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_find_last(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.predicate (§param.predicate step param.predicate)
    let predicate = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&predicate.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.findLast: predicate is not callable".into()));
    }
    // step 4 (§4 step 4)
    let mut k: usize = 0_usize;
    // step param.last (§param.last step param.last)
    let mut last = Value::Undefined;
    // step 5 (§5 step 5)
    while (k.clone() < len.clone()) {
        // step 5.a (§5.a step 5.a)
        let pk = k.clone().to_string();
        // step 5.b (§5.b step 5.b)
        let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
        // step 5.c (§5.c step 5.c)
        let test_result = crate::abstract_ops::to_boolean(&rt.call_function(predicate.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?);
        // step 5.d (§5.d step 5.d)
        if test_result.clone() {
            // step 5.d.i (§5.d.i step 5.d.i)
            last = k_value.clone();
        }
        // step 5.e (§5.e step 5.e)
        k = (k.clone() + 1_usize);
    }
    // step 6 (§6 step 6)
    return Ok(last.clone());
}

/// ECMA-262 §23.1.3.11 — Array.prototype.findLastIndex ( predicate [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_find_last_index(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.predicate (§param.predicate step param.predicate)
    let predicate = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&predicate.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.findLastIndex: predicate is not callable".into()));
    }
    // step 4 (§4 step 4)
    let mut k: usize = 0_usize;
    // step param.last (§param.last step param.last)
    let mut last = Value::Number(-1_f64);
    // step 5 (§5 step 5)
    while (k.clone() < len.clone()) {
        // step 5.a (§5.a step 5.a)
        let pk = k.clone().to_string();
        // step 5.b (§5.b step 5.b)
        let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
        // step 5.c (§5.c step 5.c)
        let test_result = crate::abstract_ops::to_boolean(&rt.call_function(predicate.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?);
        // step 5.d (§5.d step 5.d)
        if test_result.clone() {
            // step 5.d.i (§5.d.i step 5.d.i)
            last = Value::Number(k.clone() as f64);
        }
        // step 5.e (§5.e step 5.e)
        k = (k.clone() + 1_usize);
    }
    // step 6 (§6 step 6)
    return Ok(last.clone());
}

/// ECMA-262 §23.1.3.16 — Array.prototype.indexOf ( searchElement [ , fromIndex ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_index_of(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.searchElement (§param.searchElement step param.searchElement)
    let search_element = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !(0_usize < len.clone()) {
        // step 3.return (§3.return step 3.return)
        return Ok(Value::Number(-1_f64));
    }
    // step 8 (§8 step 8)
    let mut k: usize = 0_usize;
    // step 9 (§9 step 9)
    while (k.clone() < len.clone()) {
        // step 9.a (§9.a step 9.a)
        let pk = k.clone().to_string();
        // step 9.b (§9.b step 9.b)
        let k_present = rt.has_property_via(&o.clone(), &pk.clone());
        // step 9.c (§9.c step 9.c)
        if k_present.clone() {
            // step 9.c.i (§9.c.i step 9.c.i)
            let elem = rt.read_property_via(&o.clone(), &pk.clone())?;
            // step 9.c.ii (§9.c.ii step 9.c.ii)
            if crate::abstract_ops::is_strictly_equal(&search_element.clone(), &elem.clone()) {
                // step 9.c.ii.1 (§9.c.ii.1 step 9.c.ii.1)
                return Ok(Value::Number(k.clone() as f64));
            }
        }
        // step 9.d (§9.d step 9.d)
        k = (k.clone() + 1_usize);
    }
    // step 10 (§10 step 10)
    return Ok(Value::Number(-1_f64));
}

/// ECMA-262 §23.1.3.13 — Array.prototype.includes ( searchElement [ , fromIndex ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_includes(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.searchElement (§param.searchElement step param.searchElement)
    let search_element = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !(0_usize < len.clone()) {
        // step 3.return (§3.return step 3.return)
        return Ok(Value::Boolean(false));
    }
    // step 8 (§8 step 8)
    let mut k: usize = 0_usize;
    // step 9 (§9 step 9)
    while (k.clone() < len.clone()) {
        // step 9.a (§9.a step 9.a)
        let pk = k.clone().to_string();
        // step 9.b (§9.b step 9.b)
        let elem = rt.read_property_via(&o.clone(), &pk.clone())?;
        // step 9.c (§9.c step 9.c)
        if crate::abstract_ops::same_value_zero(&search_element.clone(), &elem.clone()) {
            // step 9.c.i (§9.c.i step 9.c.i)
            return Ok(Value::Boolean(true));
        }
        // step 9.d (§9.d step 9.d)
        k = (k.clone() + 1_usize);
    }
    // step 10 (§10 step 10)
    return Ok(Value::Boolean(false));
}

/// ECMA-262 §23.1.3.24 — Array.prototype.reduce ( callbackfn [ , initialValue ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_reduce(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.callbackfn (§param.callbackfn step param.callbackfn)
    let callbackfn = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&callbackfn.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.reduce: callback is not callable".into()));
    }
    // step 4 (§4 step 4)
    if !(0_usize < len.clone()) {
        // step 4.guard (§4.guard step 4.guard)
        if !(args.len() > 1) {
            // step 4.throw (§4.throw step 4.throw)
            return Err(RuntimeError::TypeError("Reduce of empty array with no initial value".into()));
        }
    }
    // step 5 (§5 step 5)
    let mut k: usize = 0_usize;
    // step 6 (§6 step 6)
    let mut accumulator = Value::Undefined;
    // step 7 (§7 step 7)
    if (args.len() > 1) {
        // step 7.a (§7.a step 7.a)
        accumulator = args.get(1).cloned().unwrap_or(Value::Undefined);
    } else {
        // step 7.b (§7.b step 7.b)
        if (k.clone() < len.clone()) {
            // step 7.b.iv (§7.b.iv step 7.b.iv)
            accumulator = rt.read_property_via(&o.clone(), &k.clone().to_string())?;
            // step 7.b.v (§7.b.v step 7.b.v)
            k = (k.clone() + 1_usize);
        }
    }
    // step 8 (§8 step 8)
    while (k.clone() < len.clone()) {
        // step 8.a (§8.a step 8.a)
        let pk = k.clone().to_string();
        // step 8.b (§8.b step 8.b)
        if rt.has_property_via(&o.clone(), &pk.clone()) {
            // step 8.c.i (§8.c.i step 8.c.i)
            let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
            // step 8.c.ii (§8.c.ii step 8.c.ii)
            accumulator = rt.call_function(callbackfn.clone().clone(), Value::Undefined.clone(), vec![accumulator.clone(), k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?;
        }
        // step 8.d (§8.d step 8.d)
        k = (k.clone() + 1_usize);
    }
    // step 9 (§9 step 9)
    return Ok(accumulator.clone());
}

/// ECMA-262 §20.1.2.18 — Object.keys ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_keys(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let obj = rt.to_object(&target.clone())?;
    // step 2 (§2 step 2)
    return Ok(rt.enumerable_own_keys(&obj.clone())?);
}

/// ECMA-262 §20.1.2.23 — Object.values ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_values(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let obj = rt.to_object(&target.clone())?;
    // step 2 (§2 step 2)
    return Ok(rt.enumerable_own_values(&obj.clone())?);
}

/// ECMA-262 §20.1.2.5 — Object.entries ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_entries(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let obj = rt.to_object(&target.clone())?;
    // step 2 (§2 step 2)
    return Ok(rt.enumerable_own_entries(&obj.clone())?);
}

/// ECMA-262 §27.2.4.7 — Promise.resolve ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn promise_resolve(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.promise_resolve_via(&x.clone())?);
}

/// ECMA-262 §27.2.4.5 — Promise.reject ( r )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn promise_reject(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.r (§param.r step param.r)
    let reason = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.promise_reject_via(&reason.clone())?);
}

/// ECMA-262 §20.1.2.12 — Object.getPrototypeOf ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_get_prototype_of(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let obj = rt.to_object(&target.clone())?;
    // step 2 (§2 step 2)
    return Ok(rt.get_prototype_of_via(&obj.clone())?);
}

/// ECMA-262 §20.1.2.21 — Object.setPrototypeOf ( O, proto )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_set_prototype_of(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.proto (§param.proto step param.proto)
    let proto = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&target.clone())?;
    // step 2 (§2 step 2)
    return Ok(rt.set_prototype_of_via(&o.clone(), &proto.clone())?);
}

/// ECMA-262 §20.1.2.14 — Object.isExtensible ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_is_extensible(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.is_extensible_via(&target.clone())?);
}

/// ECMA-262 §20.1.2.16 — Object.isFrozen ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_is_frozen(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.is_frozen_via(&target.clone())?);
}

/// ECMA-262 §20.1.2.17 — Object.isSealed ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_is_sealed(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.is_sealed_via(&target.clone())?);
}

/// ECMA-262 §20.1.2.7 — Object.freeze ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_freeze(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.object_freeze_via(&target.clone())?);
}

/// ECMA-262 §20.1.2.20 — Object.seal ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_seal(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.object_seal_via(&target.clone())?);
}

/// ECMA-262 §20.1.2.18 — Object.preventExtensions ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_prevent_extensions(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.object_prevent_extensions_via(&target.clone())?);
}

/// ECMA-262 §20.1.2.13 — Object.hasOwn ( O, P )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_has_own(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.key (§param.key step param.key)
    let key = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.object_has_own_via(&target.clone(), &key.clone())?);
}

/// ECMA-262 §20.1.2.14 — Object.is ( value1, value2 )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_is(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.value1 (§param.value1 step param.value1)
    let value1 = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.value2 (§param.value2 step param.value2)
    let value2 = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.object_is_via(&value1.clone(), &value2.clone())?);
}

/// ECMA-262 §21.1.2.2 — Number.isFinite ( number )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn number_is_finite(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.number (§param.number step param.number)
    let number = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.number_is_finite_via(&number.clone())?);
}

/// ECMA-262 §21.1.2.3 — Number.isInteger ( number )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn number_is_integer(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.number (§param.number step param.number)
    let number = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.number_is_integer_via(&number.clone())?);
}

/// ECMA-262 §21.1.2.4 — Number.isNaN ( number )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn number_is_nan(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.number (§param.number step param.number)
    let number = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.number_is_nan_via(&number.clone())?);
}

/// ECMA-262 §21.1.2.5 — Number.isSafeInteger ( number )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn number_is_safe_integer(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.number (§param.number step param.number)
    let number = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.number_is_safe_integer_via(&number.clone())?);
}

/// ECMA-262 §19.2.3 — isNaN ( number )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn global_is_nan(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.number (§param.number step param.number)
    let number = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.global_is_nan_via(&number.clone())?);
}

/// ECMA-262 §19.2.2 — isFinite ( number )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn global_is_finite(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.number (§param.number step param.number)
    let number = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.global_is_finite_via(&number.clone())?);
}

/// ECMA-262 §21.3.2.1 — Math.abs ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_abs(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("abs".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.16 — Math.floor ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_floor(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("floor".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.10 — Math.ceil ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_ceil(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("ceil".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.28 — Math.round ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_round(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("round".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.35 — Math.trunc ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_trunc(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("trunc".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.32 — Math.sqrt ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_sqrt(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("sqrt".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.9 — Math.cbrt ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_cbrt(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("cbrt".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.30 — Math.sign ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_sign(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("sign".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.14 — Math.exp ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_exp(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("exp".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.15 — Math.expm1 ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_expm1(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("expm1".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.20 — Math.log ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_log(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("log".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.21 — Math.log1p ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_log1p(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("log1p".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.22 — Math.log2 ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_log2(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("log2".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.23 — Math.log10 ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_log10(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("log10".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.29 — Math.sin ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_sin(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("sin".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.12 — Math.cos ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_cos(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("cos".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.33 — Math.tan ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_tan(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("tan".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.3 — Math.asin ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_asin(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("asin".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.2 — Math.acos ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_acos(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("acos".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.6 — Math.atan ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_atan(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("atan".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.31 — Math.sinh ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_sinh(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("sinh".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.13 — Math.cosh ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_cosh(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("cosh".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.34 — Math.tanh ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_tanh(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("tanh".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.5 — Math.asinh ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_asinh(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("asinh".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.4 — Math.acosh ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_acosh(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("acosh".to_string())), &x.clone())?);
}

/// ECMA-262 §21.3.2.7 — Math.atanh ( x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_atanh(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_unary_op_via(&Value::String(std::rc::Rc::new("atanh".to_string())), &x.clone())?);
}

/// ECMA-262 §28.1.9 — Reflect.has ( target, propertyKey )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn reflect_has(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.key (§param.key step param.key)
    let key = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.reflect_has_via(&target.clone(), &key.clone())?);
}

/// ECMA-262 §28.1.8 — Reflect.get ( target, propertyKey [ , receiver ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn reflect_get(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.key (§param.key step param.key)
    let key = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.reflect_get_via(&target.clone(), &key.clone())?);
}

/// ECMA-262 §28.1.13 — Reflect.set ( target, propertyKey, V [ , receiver ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn reflect_set(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.key (§param.key step param.key)
    let key = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step param.value (§param.value step param.value)
    let value = args.get(2).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.reflect_set_via(&target.clone(), &key.clone(), &value.clone())?);
}

/// ECMA-262 §28.1.4 — Reflect.deleteProperty ( target, propertyKey )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn reflect_delete_property(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.key (§param.key step param.key)
    let key = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.reflect_delete_property_via(&target.clone(), &key.clone())?);
}

/// ECMA-262 §28.1.12 — Reflect.ownKeys ( target )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn reflect_own_keys(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.reflect_own_keys_via(&target.clone())?);
}

/// ECMA-262 §28.1.7 — Reflect.getPrototypeOf ( target )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn reflect_get_prototype_of(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.reflect_get_prototype_of_via(&target.clone())?);
}

/// ECMA-262 §28.1.14 — Reflect.setPrototypeOf ( target, proto )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn reflect_set_prototype_of(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.proto (§param.proto step param.proto)
    let proto = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.reflect_set_prototype_of_via(&target.clone(), &proto.clone())?);
}

/// ECMA-262 §28.1.10 — Reflect.isExtensible ( target )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn reflect_is_extensible(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.reflect_is_extensible_via(&target.clone())?);
}

/// ECMA-262 §28.1.11 — Reflect.preventExtensions ( target )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn reflect_prevent_extensions(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.reflect_prevent_extensions_via(&target.clone())?);
}

/// ECMA-262 §21.3.2.27 — Math.pow ( base, exponent )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_pow(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.y (§param.y step param.y)
    let y = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_binary_op_via(&Value::String(std::rc::Rc::new("pow".to_string())), &x.clone(), &y.clone())?);
}

/// ECMA-262 §21.3.2.8 — Math.atan2 ( y, x )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_atan2(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.x (§param.x step param.x)
    let x = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.y (§param.y step param.y)
    let y = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.math_binary_op_via(&Value::String(std::rc::Rc::new("atan2".to_string())), &x.clone(), &y.clone())?);
}

/// ECMA-262 §21.3.2.25 — Math.max ( ...values )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_max(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step 1 (§1 step 1)
    return Ok(rt.math_max_via(args)?);
}

/// ECMA-262 §21.3.2.26 — Math.min ( ...values )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_min(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step 1 (§1 step 1)
    return Ok(rt.math_min_via(args)?);
}

/// ECMA-262 §21.3.2.17 — Math.hypot ( ...values )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn math_hypot(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step 1 (§1 step 1)
    return Ok(rt.math_hypot_via(args)?);
}

/// ECMA-262 §20.1.2.10 — Object.getOwnPropertyNames ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_get_own_property_names(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let obj = rt.to_object(&target.clone())?;
    // step 2 (§2 step 2)
    return Ok(rt.own_property_names_via(&obj.clone())?);
}

/// ECMA-262 §20.1.2.11 — Object.getOwnPropertySymbols ( O )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_get_own_property_symbols(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let obj = rt.to_object(&target.clone())?;
    // step 2 (§2 step 2)
    return Ok(rt.own_property_symbols_via(&obj.clone())?);
}

/// ECMA-262 §20.1.2.1 — Object.assign ( target, ...sources )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_assign(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.target (§param.target step param.target)
    let target = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.object_assign_via(&target.clone(), if args.len() > 1 { &args[1..] } else { &[] })?);
}

/// ECMA-262 §20.1.2.7 — Object.fromEntries ( iterable )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn object_from_entries(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.iter (§param.iter step param.iter)
    let iter = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.object_from_entries_via(&iter.clone())?);
}

/// ECMA-262 §21.1.3.3 — Number.prototype.toFixed ( fractionDigits )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn number_prototype_to_fixed(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.digits (§param.digits step param.digits)
    let digits = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.number_proto_to_fixed_via(&this.clone(), &digits.clone())?);
}

/// ECMA-262 §21.1.3.7 — Number.prototype.valueOf ( )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn number_prototype_value_of(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step 1 (§1 step 1)
    return Ok(rt.number_proto_value_of_via(&this.clone())?);
}

/// ECMA-262 §21.1.3.2 — Number.prototype.toExponential ( fractionDigits )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn number_prototype_to_exponential(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.digits (§param.digits step param.digits)
    let digits = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.number_proto_to_exponential_via(&this.clone(), &digits.clone())?);
}

/// ECMA-262 §21.1.3.5 — Number.prototype.toPrecision ( precision )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn number_prototype_to_precision(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.precision (§param.precision step param.precision)
    let precision = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.number_proto_to_precision_via(&this.clone(), &precision.clone())?);
}

/// ECMA-262 §20.3.3.3 — Boolean.prototype.valueOf ( )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn boolean_prototype_value_of(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step 1 (§1 step 1)
    return Ok(rt.boolean_proto_value_of_via(&this.clone())?);
}

/// ECMA-262 §20.3.3.2 — Boolean.prototype.toString ( )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn boolean_prototype_to_string(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step 1 (§1 step 1)
    return Ok(rt.boolean_proto_to_string_via(&this.clone())?);
}

/// ECMA-262 §22.1.3.1 — String.prototype.charAt ( pos )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn string_prototype_char_at(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.pos (§param.pos step param.pos)
    let pos = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.string_proto_char_at_via(&this.clone(), &pos.clone())?);
}

/// ECMA-262 §22.1.3.2 — String.prototype.charCodeAt ( pos )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn string_prototype_char_code_at(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.pos (§param.pos step param.pos)
    let pos = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    return Ok(rt.string_proto_char_code_at_via(&this.clone(), &pos.clone())?);
}

/// ECMA-262 §22.1.3.3 — String.prototype.concat ( ...args )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn string_prototype_concat(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step 1 (§1 step 1)
    return Ok(rt.string_proto_concat_via(&this.clone(), args)?);
}

/// ECMA-262 §22.1.3.28 — String.prototype.toLowerCase ( )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn string_prototype_to_lower_case(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step 1 (§1 step 1)
    return Ok(rt.string_proto_to_lower_case_via(&this.clone())?);
}

/// ECMA-262 §22.1.3.30 — String.prototype.toUpperCase ( )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn string_prototype_to_upper_case(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step 1 (§1 step 1)
    return Ok(rt.string_proto_to_upper_case_via(&this.clone())?);
}

/// ECMA-262 §22.1.3.26 — String.prototype.toLocaleLowerCase ( [ reserved1 [ , reserved2 ] ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn string_prototype_to_locale_lower_case(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step 1 (§1 step 1)
    return Ok(rt.string_proto_to_lower_case_via(&this.clone())?);
}

/// ECMA-262 §22.1.3.27 — String.prototype.toLocaleUpperCase ( [ reserved1 [ , reserved2 ] ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn string_prototype_to_locale_upper_case(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step 1 (§1 step 1)
    return Ok(rt.string_proto_to_upper_case_via(&this.clone())?);
}

/// ECMA-262 §22.1.3.32 — String.prototype.trim ( )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn string_prototype_trim(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step 1 (§1 step 1)
    return Ok(rt.string_proto_trim_via(&this.clone())?);
}

/// ECMA-262 §22.1.3.34 — String.prototype.trimStart ( )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn string_prototype_trim_start(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step 1 (§1 step 1)
    return Ok(rt.string_proto_trim_start_via(&this.clone())?);
}

/// ECMA-262 §22.1.3.33 — String.prototype.trimEnd ( )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn string_prototype_trim_end(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step 1 (§1 step 1)
    return Ok(rt.string_proto_trim_end_via(&this.clone())?);
}

/// ECMA-262 §B.2.2.1 — String.prototype.trimLeft ( )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn string_prototype_trim_left(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step 1 (§1 step 1)
    return Ok(rt.string_proto_trim_start_via(&this.clone())?);
}

/// ECMA-262 §B.2.2.2 — String.prototype.trimRight ( )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn string_prototype_trim_right(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step 1 (§1 step 1)
    return Ok(rt.string_proto_trim_end_via(&this.clone())?);
}

