//! Test wrapper that includes the generated function and tries to compile.
use crate::interp::{Runtime, RuntimeError};
use crate::value::Value;

/// ECMA-262 §23.1.3.20 — Array.prototype.map ( callbackfn [ , thisArg ] )
///
/// Generated by rusty-js-ir lowering (resolver-instance #0c).
/// Do not edit by hand; modify the IR in pilots/rusty-js-ir/derived/src/sections/.
pub fn array_prototype_map(rt: &mut Runtime, this: Value, args: &[Value])
    -> Result<Value, RuntimeError>
{
    // step param.callbackfn (§param.callbackfn step param.callbackfn)
    let callbackfn = args.get(0).cloned().unwrap_or(Value::Undefined);
    // step param.thisArg (§param.thisArg step param.thisArg)
    let this_arg = args.get(1).cloned().unwrap_or(Value::Undefined);
    // step 1 (§1 step 1)
    let o = rt.to_object(&this.clone())?;
    // step 2 (§2 step 2)
    let mut len: usize = rt.length_of_array_like(&o.clone())?;
    // step 3 (§3 step 3)
    if !rt.is_callable(&callbackfn.clone()) {
        // step 3.throw (§3.throw step 3.throw)
        return Err(RuntimeError::TypeError("Array.prototype.map: callback is not callable".into()));
    }
    // step 4 (§4 step 4)
    let a = rt.array_species_create(&o.clone(), len.clone())?;
    // step 5 (§5 step 5)
    let mut k: usize = 0_usize;
    // step 6 (§6 step 6)
    while (k.clone() < len.clone()) {
        // step 6.a (§6.a step 6.a)
        let pk = k.clone().to_string();
        // step 6.b (§6.b step 6.b)
        if rt.has_property_via(&o.clone(), &pk.clone()) {
            // step 6.c.i (§6.c.i step 6.c.i)
            let k_value = rt.read_property_via(&o.clone(), &pk.clone())?;
            // step 6.c.ii (§6.c.ii step 6.c.ii)
            let mapped = rt.call_function(callbackfn.clone().clone(), this_arg.clone().clone(), vec![k_value.clone(), Value::Number(k.clone() as f64), o.clone()])?;
            // step 6.c.iii (§6.c.iii step 6.c.iii)
            { rt.create_data_property_or_throw(&a.clone(), &pk.clone(), mapped.clone())?; Value::Undefined };
        }
        // step 6.d (§6.d step 6.d)
        k = (k.clone() + 1_usize);
    }
    // step 7 (§7 step 7)
    return Ok(a.clone());
}

